/* Source-derived visual compositions. No generated research observations. */
(() => {
 'use strict';
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], id=document.body.dataset.project;
 if(!id)return;document.body.classList.add('composition-edition');
 const A='assets/composition/', E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const node=(html,cls='')=>{const n=document.createElement('section');n.className='comp-panel '+cls;n.innerHTML=html;return n;};
 const heading=(code,title,extra='')=>`<header class="comp-heading"><div><span class="comp-code">${code}</span><h3>${title}</h3></div>${extra}</header>`;
 const svg=(w,h,body,label)=>`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${E(label)}"><title>${E(label)}</title>${body}</svg>`;
 const crop=(key,box,dim,label)=>`<svg viewBox="${box}" role="img" aria-label="${E(label)}"><title>${E(label)}</title><image href="${A+key}.webp" width="${dim[0]}" height="${dim[1]}"/></svg>`;
 const source=s=>`<p class="comp-source">${s}</p>`;
 const chapter=n=>$(`#chapter-${n} .chapter-visuals`);
 const replace=(n,p)=>chapter(n)?.replaceChildren(p);
 const photo=(key,alt)=>`<img src="${A+key}.webp" alt="${E(alt)}" loading="lazy">`;
 function choose(root,attr,fn){const bs=$$(`[${attr}]`,root);const set=i=>{bs.forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));fn(i);};bs.forEach((b,i)=>{b.onclick=()=>set(i);b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();e.stopPropagation();const j=e.key==='Home'?0:e.key==='End'?bs.length-1:(i+(e.key==='ArrowRight'?1:-1)+bs.length)%bs.length;bs[j].focus();set(j);});});set(0);}
 const tabs=(labels,attr)=>`<div class="comp-tabs" role="group">${labels.map((x,i)=>`<button ${attr}="${i}" aria-pressed="${i===0}">${x}</button>`).join('')}</div>`;
 function diagramKeyboard(root,attr,fn){$$(`[${attr}]`,root).forEach(n=>{n.setAttribute('role','button');n.setAttribute('tabindex','0');n.addEventListener('click',()=>fn(Number(n.getAttribute(attr))));n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn(Number(n.getAttribute(attr)));}});});}
 const fail=(p,message)=>{p.append(node(`<p role="status">${message}。原项目内容仍可在本页查看。</p>`));};

 if(id==='rallylens')rally();
 if(id==='privacy-city')privacy();
 if(id==='tennisatom')tennis();
 if(id==='baseball')baseball();
 if(id==='artemis')artemis();
 if(id==='bronze')bronze();
 if(id==='afterglow')afterglow();

 function rally(){
  const films=$('#project-videos');if(films){$('.case-hero').after(films);$('h2',films).textContent='先看一段共同训练。';films.classList.add('comp-opening-films');}
  const field=node(heading('A / B · SYNCHRONIZED EVIDENCE','两个机位，指向同一个交换。','<span class="comp-big">A↔B</span>')+`<div class="comp-dual-camera"><figure><span>CAMERA A / 主视角</span>${crop('figS6_rallylens_layer1','68 132 1108 622',[1822,1376],'机位A，原型双机位示例的主画面')}</figure><figure><span>CAMERA B / 反向视角</span>${crop('figS6_rallylens_layer1','902 568 249 140',[1822,1376],'机位B，原型截图中的反向机位')}<figcaption>从 supplement 的原型双视角中拆出，保留原画面清晰度。</figcaption></figure></div><div class="comp-synchrony"><b>G01_02</b><span>片段时间 <strong>6.80 s</strong></span><span>同一事件 <strong>#02</strong></span><span>方向 <strong>P02 → P01</strong></span></div><div class="comp-evidence-ribbon">${[['01','双机位视频','检查动作与来球'],['02','当场目标卡','记录练习意图'],['03','分别回顾','保留双方解释'],['04','教练读片','添加独立视角']].map(x=>`<article><b>${x[0]}</b><h4>${x[1]}</h4><p>${x[2]}</p></article>`).join('')}</div>`+source('画面来源：supplement Fig. S6。此处是同一原型事件的静态双视角，不将两张图伪装为可同步播放的原始双路视频。'), 'comp-rally-field');
  const atlas=$('.depth-panel',chapter(1));replace(1,field);if(atlas)chapter(1).append(atlas);
  const bench=node(heading('EVIDENCE WORKSPACE / RECONSTRUCTED','相同目标，不同解释。','<span class="comp-big">≠</span>')+tabs(['01 / 当场目标','02 / 双方解释','03 / 模型分解'],'data-account-mode')+`<div class="comp-accounts-view" aria-live="polite"></div>`+source('依据 G01_02 的目标卡与 supplement Fig. S7 重新排版。中文为意译；陈述来源和范围分别保留。模型图来自逐事件 CSV，不自动裁定哪位球员“说得对”。'),'comp-accounts');
  $('.project-workbench')?.replaceWith(bench);
  choose(bench,'data-account-mode',i=>{
   const view=$('.comp-accounts-view',bench);
   if(i===0)view.innerHTML=`<div class="comp-account-pair"><article><span class="comp-code">P01 / 当场 · 接球方</span><h4>落点 / 线路</h4><p>希望变化方向，练习后场来球。</p><div class="comp-path-symbol">↗<span>CHANGE</span>↘</div></article><article><span class="comp-code">P02 / 当场 · 喂球方</span><h4>落点 / 线路</h4><p>希望重复相同的球，接近比赛条件。</p><div class="comp-path-symbol">→<span>REPEAT</span>→</div></article></div><div class="comp-conclusion"><b>目标词相同 ≠ 提供条件的方式相同</b><p>目标卡保存“想练什么”与“怎样给球”，而不从动作替双方补写意图。</p></div>`;
   if(i===1)view.innerHTML=`<div class="comp-account-pair"><article><span class="comp-code">P01 / 事后回顾</span><h4>顺着来球，<br>自然地继续。</h4><p>认为片段并非刻意组织，只是在跟随飞来的球。</p><small>跨片段陈述 · 本片段内无明确锚点</small></article><article><span class="comp-code">P02 / 事后回顾</span><h4>有意安排，<br>在做网前练习。</h4><p>认为前两段完整交换是在有意练习，并且相对稳定。</p><small>跨片段陈述 · 候选范围 R2–R3 为推定</small></article></div><div class="comp-source-bridge"><span>P01 ○</span><i></i><strong>同一片段<br>不强制达成共识</strong><i></i><span>□ P02</span></div><aside class="comp-coach"><span class="comp-code">COACH C01 / 独立读片</span><h4>教练意见保留自己的时间范围。</h4><p>认为球员似乎想练网前球，却经常把球挑起，落点还不够稳定。</p><small>同一阶段的另一窗口 · 源时间 594 s；不是当前 6.80 s 事件的逐拍评价。</small></aside>`;
   if(i===2){view.innerHTML='<div data-parent-plot><p>正在读取事件模型表…</p></div>';fetch(A+'rally-events.json').then(r=>r.json()).then(data=>{if(!view.querySelector('[data-parent-plot]'))return;const e=data.find(x=>x.dpe_id==='DPE_G01_02'&&x.physical_event_index===2);view.innerHTML=`<div class="comp-model-head"><div><span class="comp-code">EVENT #02 / P02 → P01 / 6.80 s</span><h4>机会与回应，<br>不是同一个数。</h4><p>○ Offer：来球提供的条件<br>■ Actual：回应后可观察到的实现</p></div><div class="comp-goal-readout"><b>${e.goal_offer_score.toFixed(2)}</b><span>→</span><b>${e.goal_actual_score.toFixed(2)}</b><small>所选目标头 · 落点 / 线路 · 0—100 模型尺度</small></div></div>${parentPlot(e)}`;}).catch(()=>fail(view,'模型数据暂时未载入'));}
  });
  const timeline=node(heading('G01_02 / EVENT REGISTER','每一拍，都有自己的位置。','<span class="comp-big">16</span>')+`<div class="comp-timeline-controls">${tabs(['全片段','0—10 s','5—15 s','10—20 s','15—25 s','20—30 s'],'data-rally-window')}<label>事件<select aria-label="选择逐事件记录" data-event-select></select></label></div><div class="comp-plot-scroll" tabindex="0" aria-label="事件时间线，可横向滚动"><div data-rally-timeline></div></div><div class="comp-event-detail" aria-live="polite"></div><details><summary>展开当前事件的八维模型分解</summary><div data-event-model></div></details>`+source('逐事件数据来自 DPE逐事件明细_12个DPE_含Goal8D.csv。片段起点对应源时间 525 s；点位置为真实时间，圆 / 方 / 菱形区分两个方向与未知。窗口为重叠的 10 s 区间，步长 5 s。'),'comp-rally-events');replace(4,timeline);
  fetch(A+'rally-events.json').then(r=>r.json()).then(all=>{const events=all.filter(e=>e.dpe_id==='DPE_G01_02');let current=1,windowIndex=0;const select=$('[data-event-select]',timeline);select.innerHTML=events.map((e,i)=>`<option value="${i}">事件 ${e.physical_event_index} · ${(e.event_time_a_s-525).toFixed(2)} s</option>`).join('');select.value='1';
   const draw=()=>{const x=t=>145+t/30*865,y=d=>d==='A_to_B'?85:d==='B_to_A'?210:148;let body='';[0,5,10,15,20,25,30].forEach(t=>body+=`<path d="M${x(t)} 48V270" class="comp-grid-line"/><text x="${x(t)}" y="300" text-anchor="middle">${t}s</text>`);
    if(windowIndex){const t=(windowIndex-1)*5;body+=`<rect x="${x(t)}" y="50" width="${865/3}" height="210" class="comp-window-band"/>`;}
    body+='<text x="10" y="90">○ P01→P02</text><text x="10" y="153">◇ 未确认</text><text x="10" y="215">□ P02→P01</text>';
    // R1 = event 1, R2 = 2–6, R3 = 7–13, R4 = 14–16, per Fig.S6.
    const bounds=[[0,0],[1,5],[6,12],[13,15]];bounds.forEach(([a,b],j)=>{body+=`<text x="${x(events[a].event_time_a_s-525)}" y="28">R${j+1}</text>`;for(let i=a;i<b;i++){const s=events[i],t=events[i+1];body+=`<path d="M${x(s.event_time_a_s-525)} ${y(s.direction)}L${x(t.event_time_a_s-525)} ${y(t.direction)}" class="comp-event-link" ${s.direction==='unknown'||t.direction==='unknown'?'stroke-dasharray="5 6"':''}/>`;}});
    events.forEach((e,i)=>{const xx=x(e.event_time_a_s-525),yy=y(e.direction);body+=`<g data-rally-event="${i}" aria-label="事件 ${i+1}，${(e.event_time_a_s-525).toFixed(2)} 秒" class="comp-event ${i===current?'selected':''}"><circle class="event-hit-area" cx="${xx}" cy="${yy}" r="20"/>${e.direction==='A_to_B'?`<circle cx="${xx}" cy="${yy}" r="7"/>`:e.direction==='B_to_A'?`<rect x="${xx-7}" y="${yy-7}" width="14" height="14"/>`:`<path d="M${xx} ${yy-9}l9 9-9 9-9-9Z"/>`}<text x="${xx}" y="${yy+31}" text-anchor="middle">${i+1}</text></g>`;});
    $('[data-rally-timeline]',timeline).innerHTML=svg(1060,320,body,'16个事件、四个回合、两个方向与未知状态');diagramKeyboard(timeline,'data-rally-event',i=>{current=i;select.value=String(i);draw();});
    const e=events[current];$('[data-rally-event="'+current+'"]',timeline)?.setAttribute('aria-pressed','true');$('.comp-event-detail',timeline).innerHTML=`<strong>${String(current+1).padStart(2,'0')}</strong><div><span class="comp-code">${E(e.gold_shot_id)}</span><h4>${(e.event_time_a_s-525).toFixed(2)} s · ${e.direction==='A_to_B'?'P01 → P02':e.direction==='B_to_A'?'P02 → P01':'方向未确认'}</h4><p>源视频时间 ${e.event_time_a_s.toFixed(3)} s · ${e.actual_status==='observed_no_response_zero'?'未出现可观察回应：Actual 为 0。':e.actual_status==='observed_contact_model_estimate'?'存在接触证据：可以展开 Actual 模型估计。':'证据状态：'+E(e.actual_status)}</p></div>`;$('[data-event-model]',timeline).innerHTML=parentPlot(e);
   };select.onchange=()=>{current=+select.value;draw();};choose(timeline,'data-rally-window',i=>{windowIndex=i;draw();});
  }).catch(()=>fail(timeline,'逐事件表未载入'));
  replace(3,node(heading('ALGORITHM / DATA CONTRACT','两种分析尺度，一套可追溯索引。','<span class="comp-big">↳</span>')+`<div class="comp-data-contract"><div class="comp-contract-input"><b>双机位视频</b><span>人工核验事件 / 目标卡 / 陈述</span><code>case_id + time + direction + evidence_id</code></div><div class="comp-contract-branches"><article><span class="comp-code">EVENT / PracticeOpportunity</span><h4>一拍提供了什么条件？</h4><div class="comp-8d-bars">${Array.from({length:8},(_,i)=>`<span>${i+1}</span>`).join('')}</div><p>8D Offer → 接触证据检查 → 8D Actual</p><small>目标无关描述与所选目标头分别保存。</small></article><article><span class="comp-code">WINDOW / DyadicRelationState</span><h4>一段交换如何组织？</h4>${svg(420,130,Array.from({length:5},(_,i)=>`<rect x="${15+i*55}" y="${10+i*22}" width="110" height="15" fill="currentColor" opacity="${.2+i*.12}"/>` ).join(''),'10秒窗口，每5秒前进')}<p>10 s 窗口 / 5 s 步长</p><small>搭档历史、下一段回应与身体协变分开分析。</small></article></div><div class="comp-contract-output"><b>对齐索引</b><span>画面 ← 事件 → 模型候选</span><b>共同检查</b><span>陈述 ↔ 证据 ↔ 下一步计划</span></div></div>`+source('结构依据 supplement 的 PracticeOpportunity、DyadicRelationState 与双路径目标头。计算候选辅助检查，不等同训练效果、关系质量或准确率提升。')));
 }
 function parentPlot(e){const dims=[['response_continuity','回应连续'],['technique_transition','技术转换'],['placement_line_control','落点 / 线路'],['spatial_coverage','空间覆盖'],['movement_demand','移动需求'],['recovery_readiness','回位准备'],['rhythm_stability_variation','节奏变化'],['decision_pressure','决策压力']];return `<div class="comp-parent-plot"><div class="comp-axis-label"><span>○ Offer / ■ Actual</span><span>模型尺度 0—100 · 非成功率</span></div>${dims.map(([key,name])=>{const a=e['offer_'+key],b=e['actual_'+key];return `<div class="comp-dumbbell"><span>${name}</span><div><i style="left:0"></i><i style="left:50%"></i><i style="left:100%"></i>${a!==null?`<em style="left:${a}%">○</em>`:''}${b!==null?`<strong style="left:${b}%">■</strong>`:''}</div><code>${a===null?'—':a.toFixed(2)} / ${b===null?'—':b.toFixed(2)}</code></div>`;}).join('')}<div class="comp-dumbbell comp-ticks"><span></span><div><span>0</span><span>50</span><span>100</span></div><span></span></div></div>`;}

 function privacy(){
  const groups=[['A','行为节奏',8,'点击、滚动与决定的时间模式。'],['B','阅读行为',8,'停留、完成、回看与条款参与。'],['C','风险偏好',10,'试探问题与不同权限的拒绝倾向。'],['D','情境特征',8,'设备、时间压力、资源和社交情境。'],['E','时序演变',6,'决定时间、疲劳与阅读深度的变化。'],['F','交互效应',8,'阅读×风险、疲劳×稀缺等交叉特征。']];
  const p=node(heading('FEATURE ATLAS / 48 INPUTS','把行为，组织成可检查的输入。','<span class="comp-big">48</span>')+`<div class="comp-feature-layout"><div><div class="comp-feature-grid" role="group" aria-label="48个特征"></div><div class="comp-feature-legend">${groups.map((g,i)=>`<button data-feature-group="${i}" aria-pressed="${i===0}">${g[0]} / ${g[1]} <b>${g[2]}</b></button>`).join('')}</div></div><aside data-feature-detail aria-live="polite"></aside></div>`+source('特征名称与分组取自 feature_engine.py：8 / 8 / 10 / 8 / 6 / 8，共 48 维。方格表示输入字段，不表示隐私风险高低。实验数据由模拟器生成。'),'comp-feature-atlas');chapter(2)?.prepend(p);
  fetch(A+'privacy-features.json').then(r=>r.json()).then(names=>{let offset=0;const rows=groups.map((g,i)=>{const start=offset;offset+=g[2];return names.slice(start,offset).map((n,j)=>({n,index:start+j,group:i}));}).flat();$('.comp-feature-grid',p).innerHTML=rows.map(r=>`<button data-feature="${r.index}" data-group="${r.group}" aria-label="${E(r.n)}"><small>${groups[r.group][0]}</small><b>${String(r.index+1).padStart(2,'0')}</b></button>`).join('');let selectedGroup=0;
   const detail=i=>{const r=rows[i],g=groups[r.group];$('[data-feature-detail]',p).innerHTML=`<span class="comp-code">${g[0]} / ${g[1]} / ${g[2]} FEATURES</span><h4>${String(i+1).padStart(2,'0')}</h4><code>${r.n}</code><p>${g[3]}</p><div class="comp-mini-contract">原始记录 → 归一化 [0,1] → 输入向量</div>`;$$('[data-feature]',p).forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.feature===i)));};
   choose(p,'data-feature-group',i=>{selectedGroup=i;$$('[data-feature]',p).forEach(b=>b.classList.toggle('in-group',+b.dataset.group===i));detail(rows.find(r=>r.group===i).index);});$$('[data-feature]',p).forEach(b=>b.onclick=()=>detail(+b.dataset.feature));
  }).catch(()=>fail(p,'特征字典未载入'));
  const budget=node(heading('PARAMETER ANATOMY / EXACT DIMENSIONS','5,249 个参数，放在哪里？','<span class="comp-big">Σ</span>')+`<div class="comp-parameter-bars">${[['48 → 64',3136,'48 × 64 + 64'],['64 → 32',2080,'64 × 32 + 32'],['32 → 1',33,'32 × 1 + 1']].map((x,i)=>`<div><span>${x[0]}</span><div class="comp-parameter-track"><i style="width:${x[1]/5249*100}%"></i></div><b>${x[1].toLocaleString()}</b><code>${x[2]}</code></div>`).join('')}</div><div class="comp-training-split"><span style="flex:3500"><b>3,500</b>训练 / 权重更新</span><span style="flex:750"><b>750</b>验证 / 选择</span><span style="flex:750"><b>750</b>测试 / 评估</span></div><div class="comp-question-grid"><article><b>排序</b><h4>AUC</h4><p>正例是否通常排在负例前？</p></article><article><b>分类</b><h4>F1</h4><p>选定阈值后，如何平衡查准与查全？</p></article><article><b>概率</b><h4>ECE / Brier</h4><p>给出的信心与实际结果是否一致？</p></article></div>`+source('参数条从零起算，占总参数量的比例；数据划分对应原五模型比较的 5,000 合成样本实验，不混用其他基线轮次。'),'comp-privacy-budget');replace(4,budget);
 }

 function tennis(){
  const existing=$('.project-workbench');if(existing){$('.director-material',existing)?.remove();$('.portrait-director>aside',existing)?.remove();$('.portrait-director',existing)?.classList.add('comp-single-cinema');$('.workbench-bar',existing)?.remove();const caption=$('.studio-boundary',existing);if(caption)caption.textContent='选择编号观看五支既有成片；下方展开数据管线与视觉分层，呈现从运动记录到个人表达的制作过程。';}
  $('.experience-heading h2').textContent='五个人，五种影像表达。';$('.experience-heading>p:last-child')?.remove();
  replace(1,node(heading('VISUAL THESIS / BODY AS PORTRAIT','运动信息，成为肖像的构图。','<span class="comp-big">↗</span>')+`<div class="comp-tennis-poster"><div class="comp-poster-fragment">${crop('tennis-poster','130 350 1040 960',[1273,1800],'原主视觉海报的身体、轨迹与测量线局部')}</div><div class="comp-poster-type"><span class="comp-code">THE PORTRAIT OF THE BODY</span><h4>不只看<br>打得如何。<br><em>还看见你。</em></h4><p>从专业转播的分析语言出发，将动作、文字与风格交给个人表达。</p><div class="comp-triad"><span>身体<br><b>BODY</b></span><span>信号<br><b>SIGNAL</b></span><span>叙事<br><b>STORY</b></span></div></div></div>`+source('视觉主体拆自原主视觉海报，测量标记为原海报的设计表达，不作为新增检测结果。')));
  const items=[['视频输入','4K / 1080p 运动素材','保留视频与时间基准，后续信号与输出回到同一段动作。'],['骨骼提取','MediaPipe · 33 关键点','将身体结构转成关键点序列，支持骨骼、角度与动作特效。'],['球路分析','TrackNetV2 · 轨迹与事件','检测球轨迹，连接击球、弹跳等事件与后续视觉触发。'],['特效渲染','p5.js / WebGL','运动信号进入实时视觉表达，让轨迹、冲击和节奏形成画面。'],['AI 内容','视频 / 图文 / 旁白三路','MatchBundle 共用输入，分发到风格化影像、海报与旁白脚本。'],['后期合成','FFmpeg · 多轨','组织动态文字、声音、特效与原视频，输出连贯成片。'],['交付设施','输出 / 分发 / 复用','将分析、风格选择、合成与媒体输出连接为完整制作过程。']];
  const p=node(heading('SEVEN MODULES / ONE DATA CONTRACT','从一段视频，到多种表达。','<span class="comp-big">07</span>')+`<div class="comp-plot-scroll"><div class="comp-tennis-pipeline"></div></div><div class="comp-pipeline-readout" aria-live="polite"></div>`+tabs(items.map((x,i)=>`${i+1} / ${x[0]}`),'data-tennis-node')+source('依据最终汇报第 16—19、26 页重绘。节点是原系统模块；连线表达数据依赖，不表示耗时或实时吞吐。'),'comp-tennis-system');replace(3,p);
  const positions=[[55,65],[55,240],[55,415],[680,65],[680,240],[960,150],[960,360]];
  $('.comp-tennis-pipeline',p).innerHTML=svg(1220,560,`<defs><marker id="tc-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3 0 6" fill="currentColor"/></marker></defs><path d="M280 105H345V455H280M280 280H380M345 280H420M620 280H652V105H675M652 280H675M905 105H930V190H952M905 280H930V190M1070 230V352" class="comp-wire" marker-end="url(#tc-arrow)"/><rect x="420" y="160" width="200" height="250" class="comp-bundle"/><text x="443" y="205" class="comp-svg-code">DATA CONTRACT</text><text x="443" y="250" class="comp-svg-title">MatchBundle</text><text x="443" y="285">{ JSON }</text><text x="443" y="333">视频 · 姿态 · 球路</text><text x="443" y="364">事件 · 风格 · 时间</text>${items.map((x,i)=>`<g data-tennis-svg="${i}" aria-label="${x[0]}"><rect x="${positions[i][0]}" y="${positions[i][1]}" width="225" height="90"/><text x="${positions[i][0]+18}" y="${positions[i][1]+27}" class="comp-svg-code">M${i+1}</text><text x="${positions[i][0]+18}" y="${positions[i][1]+62}" class="comp-svg-title">${x[0]}</text></g>`).join('')}`,'TennisAtom 七模块管线，以MatchBundle连接分析和内容生成');
  choose(p,'data-tennis-node',i=>{$$('.comp-tennis-pipeline g',p).forEach((n,j)=>n.classList.toggle('active',i===j));$('.comp-pipeline-readout',p).innerHTML=`<b>M${i+1}</b><div><h4>${items[i][0]} / ${items[i][1]}</h4><p>${items[i][2]}</p></div>`;});diagramKeyboard(p,'data-tennis-svg',i=>$(`[data-tennis-node="${i}"]`,p).click());
  const layers=node(heading('TRANSPARENCY LAB / SOURCE LAYERS','把信号叠进一个身体。','<span class="comp-big">＋</span>')+`<div class="comp-layer-lab"><div class="comp-layer-stage"><svg viewBox="0 0 1200 1800" role="img" aria-label="原项目透卡分层组合，示意非实测"><image href="${A}tennis-base.webp" width="1200" height="1800"/><g data-tennis-layer="skeleton"><image href="${A}tennis-skeleton.webp" width="1200" height="1800"/></g><g data-tennis-layer="fx"><image href="${A}tennis-fx.webp" width="1200" height="1800"/></g></svg><span class="comp-layer-credit">原项目风格参考 / 透卡设计 · 非团队球员实测</span></div><aside><span class="comp-code">RAW → SIGNAL → EXPRESSION</span><h4>同一动作，<br>不同观看方式。</h4><p>保留身体作为共同锚点，再叠加骨骼与漫画层。原图中的标注属于视觉提案，不增加新的动作识别结论。</p><label><input type="checkbox" data-toggle-layer="skeleton" checked> 骨骼 / 动作结构</label><label><input type="checkbox" data-toggle-layer="fx" checked> 漫画 / 风格表达</label><label>原影像可见度<input type="range" min="0" max="100" value="40" data-layer-opacity aria-label="原影像可见度"></label><p class="comp-source">源文件：透卡 / 底图、骨骼图、特效图。保留透明层，而不是重新截一张合成截图。</p></aside></div>`,'comp-tennis-layers');replace(4,layers);const base=$('.comp-layer-stage svg>image',layers);base.style.opacity='.4';$$('[data-toggle-layer]',layers).forEach(c=>{c.onchange=()=>{$(`[data-tennis-layer="${c.dataset.toggleLayer}"]`,layers).style.display=c.checked?'':'none';};});$('[data-layer-opacity]',layers).oninput=e=>base.style.opacity=String(+e.target.value/100);
  replace(5,node(heading('PROJECT FILM / 创作系统','从输入、分析，到最终成片。','<span class="comp-big">▶</span>')+`<div class="comp-intro-film"><video controls preload="metadata" playsinline src="media/tennis-introduction.mp4" aria-label="TennisAtom 项目介绍视频"></video></div><a class="comp-external" href="https://www.bilibili.com/video/BV1Us3F6LEyz/" target="_blank" rel="noopener">Bilibili / 项目介绍 ↗</a>`+source('播放原项目文件夹中的《介绍视频.mp4》。上方五支影片用于看个人表达，本片用于看整体制作系统。')));
 }

 function baseball(){
  // One hero in the opening only; the case chapters contain new data views.
  $('#design-decisions img[src*="baseball-web-hero"]')?.closest('figure')?.remove();
  const p=node(heading('PITCH / IMPACT · SAME SEASON','一端控制来球，一端创造击球。','<span class="comp-big">×</span>')+`<div class="comp-baseball-duet"><article><span class="comp-code">YAMAMOTO / PITCH</span><h4>控制<br>CONTROL.</h4><div data-pitch-hist></div><p>投球出手速度 / mph</p></article><article><span class="comp-code">OHTANI / IMPACT</span><h4>创造<br>IMPACT.</h4><div data-hit-hist></div><p>击球初速 / mph</p></article></div><div class="comp-baseball-year">${tabs(['2024','2025','2026'],'data-hist-year')}<output data-hist-readout aria-live="polite"></output></div>`+source('直接汇总原提交 CSV。每格为 5 mph 区间，纵轴为记录数，两图独立标注上限；不是两位球员能力高低的直接比较。缺失速度不填 0。2026 只代表源文件覆盖日期。'),'comp-baseball-comparison');replace(1,p);
  fetch('assets/baseball-records.json').then(r=>r.json()).then(data=>{choose(p,'data-hist-year',i=>{const year=String(2024+i);const hist=(rows,key,lo,hi,target)=>{const valid=rows.filter(r=>String(r.game_date).startsWith(year)&&Number.isFinite(r[key])&&r[key]>0),bins=Array.from({length:(hi-lo)/5},()=>0);valid.forEach(r=>{const j=Math.floor((r[key]-lo)/5);if(j>=0&&j<bins.length)bins[j]++;});const max=Math.max(1,...bins),w=520,h=230;$(target,p).innerHTML=svg(w,h,`<text x="35" y="22">记录数 / max ${max}</text><path d="M35 35V192H495" class="comp-grid-line"/>${bins.map((n,j)=>`<rect x="${38+j*(450/bins.length)}" y="${190-n/max*143}" width="${450/bins.length-3}" height="${n/max*143}" fill="currentColor"><title>${lo+j*5}—${lo+(j+1)*5} mph：${n} 条</title></rect>`).join('')}${[lo,(lo+hi)/2,hi].map(t=>`<text x="${38+(t-lo)/(hi-lo)*450}" y="218" text-anchor="middle">${t}</text>`).join('')}`,'原CSV速度直方图');return valid.length;};const a=hist(data.pitch,'release_speed',60,110,'[data-pitch-hist]'),b=hist(data.bat,'launch_speed',0,125,'[data-hit-hist]');$('[data-hist-readout]',p).textContent=`${year} / 有效速度记录：投球 ${a.toLocaleString()} · 击球 ${b.toLocaleString()}`;});}).catch(()=>fail(p,'速度分布数据未载入'));
  const steps=[['INGEST','四份 CSV','投手 / 打者 / 球队','在逐球数据和球队汇总之间区分记录单位，建立字段字典。'],['TRANSFORM','从记录到视图','清理 / 分组 / 筛选','按年份、球种和球员筛选；无效坐标保留缺失，不填入零点。'],['ENCODE','空间与统计','ECharts / Three.js','位置进入坐标，分组进入颜色，时间进入序列；图表和空间视图承担不同解释任务。'],['NAVIGATE','阅读与控制','React / GSAP / Lenis','React 保持当前选择；滚动组织章节与阅读节奏，过滤控件提供局部检查入口。']];
  const sourcePitch=$('.folio-pitch-reader',chapter(2));
  const pipe=node(heading('DATA SCAPE / READING SYSTEM','数据不变，阅读尺度改变。','<span class="comp-big">04</span>')+`<div class="comp-pipeline-art">${steps.map((s,i)=>`<button data-bb-pipe="${i}" aria-pressed="${i===0}"><span class="comp-code">0${i+1} / ${s[0]}</span><div class="comp-pipe-symbol" data-symbol="${i}"></div><h4>${s[1]}</h4><p>${s[2]}</p></button>`).join('')}</div><div class="comp-pipeline-readout" data-bb-pipe-detail aria-live="polite"></div>`+source('对应原网页与提交 PDF 的数据架构、算法提炼和交互关系；下方球种图继续展开同一组源数据。'),'comp-baseball-pipeline');replace(2,pipe);if(sourcePitch)chapter(2).append(sourcePitch);
  const glyphs=[Array.from({length:4},(_,i)=>`<rect x="${25+i*34}" y="${25+i*18}" width="155" height="70" fill="none" stroke="currentColor"/><path d="M${35+i*34} ${48+i*18}h125m-125 17h80" stroke="currentColor"/>`).join(''),`<path d="M20 30H275L185 100V165L110 195V100Z" fill="none" stroke="currentColor"/><path d="M65 52H230M90 70H205M133 107V155" stroke="currentColor"/><circle cx="148" cy="173" r="8" fill="currentColor"/>`,`<path d="M25 20V185H275" stroke="currentColor" fill="none"/>${[[50,165],[78,140],[110,147],[144,88],[178,105],[213,66],[250,43]].map(([x,y],j)=>`<circle cx="${x}" cy="${y}" r="${j%2?7:10}" fill="currentColor"/>`).join('')}`,`<rect x="30" y="20" width="240" height="160" fill="none" stroke="currentColor"/><path d="M30 50H270M185 50V180M48 78H163M48 96H120M48 133H157" stroke="currentColor"/><rect x="203" y="68" width="47" height="60" fill="currentColor"/><path d="M223 141v24m-9-9 9 9 9-9" fill="none" stroke="currentColor"/>`];$$('[data-symbol]',pipe).forEach((n,i)=>n.innerHTML=svg(300,215,glyphs[i],steps[i][1]));choose(pipe,'data-bb-pipe',i=>$('[data-bb-pipe-detail]',pipe).innerHTML=`<b>0${i+1}</b><div><h4>${steps[i][1]}</h4><p>${steps[i][3]}</p></div>`);
 }

 function artemis(){
   const films=[
    {key:'gameplay',label:'实机 / 03:50',title:'从地图探索，到构筑与战斗。',text:'在同一段实机中查看六边形地图、背包构筑和战斗反馈，观察规则如何进入玩家操作。',cues:[[16,'地图 / 六边形空间'],[71,'背包 / 构筑界面'],[136,'移动 / 场景探索'],[191,'战斗 / 遭遇反馈']]},
    {key:'cutscene-one',label:'过场 01 / 01:27',title:'破碎的月亮，重建的秩序。',text:'用巨幅 CG、动态文字与剪辑组织世界观：从灾变、重建，到集体承诺与另一种选择。',cues:[[6,'文字 / 世界的开场'],[27,'断裂 / 动态排版'],[51.5,'承诺 / 群像'],[72.5,'异议 / 实验室']]},
    {key:'cutscene-two',label:'过场 02 / 01:41',title:'从仰望，到真实的航天记忆。',text:'绘制场景与历史航天影像交替出现，让虚构探索与真实航天记忆相接。历史资料镜头是成片引用素材。',cues:[[7.1,'发射 / 绘制场景'],[31.3,'1957 / 历史资料'],[59.5,'飞行 / 资料影像'],[83.7,'登月 / 资料影像']]},
    {key:'concept-film',label:'理念片 / 04:32',title:'美术、机制与航天叙事，放在同一条线上。',text:'原理念片将角色设定、构筑玩法、过场表达与航天资料组织成完整的项目陈述。',cues:[[19.1,'角色 / 造型设定'],[84.4,'构筑 / 玩法说明'],[160.6,'世界 / 过场叙事'],[226,'航天 / 历史资料']]}
   ];
   const link=window.PORTFOLIO.projects.find(x=>x.id==='artemis').links[0][1];
   const cinema=node(heading('ARTEMIS / FILM ROOM','先进入世界，再看它如何运转。','<span class="comp-big">▶</span>')+tabs(films.map(f=>f.label),'data-artemis-movie')+`<div class="comp-artemis-cinema"><div class="comp-artemis-screen"><video controls playsinline preload="metadata" aria-label="Artemis 项目影片" poster="${A}artemis-gameplay.webp" src="media/artemis-gameplay.mp4"></video></div><aside aria-live="polite"><div data-movie-description></div><nav class="comp-film-cues" aria-label="当前影片章节"></nav></aside></div><div class="comp-film-links"><span>实机 · 过场 · 理念 / 原项目成片</span><a href="${E(link)}" target="_blank" rel="noopener">小红书实机原发布 ↗</a><a href="https://www.bilibili.com/video/BV1BurDBCEQP/" target="_blank" rel="noopener">Bilibili 理念片 ↗</a></div>`,'comp-artemis-film');$('.case-hero').after(cinema);
   cinema.id='project-films';
   const filmEntry=document.createElement('a');filmEntry.href='#project-films';filmEntry.textContent='▶ FILM / 项目影片';$('.case-toc')?.prepend(filmEntry);
   const player=$('video',cinema);let filmIndex=0,seekListener=null;
   const seek=time=>{if(seekListener){player.removeEventListener('loadedmetadata',seekListener);seekListener=null;}const position=()=>{player.currentTime=Math.min(time,Number.isFinite(player.duration)?player.duration-.01:time);player.pause();};if(player.readyState)position();else{seekListener=()=>{position();seekListener=null;};player.addEventListener('loadedmetadata',seekListener,{once:true});player.load();}};
   const setMovie=i=>{if(seekListener){player.removeEventListener('loadedmetadata',seekListener);seekListener=null;}const f=films[i];if(filmIndex!==i||!player.currentSrc){player.pause();player.src=`media/artemis-${f.key}.mp4`;player.poster=`${A}artemis-${f.key}.webp`;player.load();}filmIndex=i;player.setAttribute('aria-label',`Artemis ${f.label}`);$('[data-movie-description]',cinema).innerHTML=`<span class="comp-code">0${i+1} / ${f.key.replaceAll('-',' ')}</span><h4>${f.title}</h4><p>${f.text}</p>`;$('.comp-film-cues',cinema).innerHTML=f.cues.map(([t,label],j)=>`<button data-movie-cue="${j}" aria-pressed="false"><time>${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}</time><span>${label}</span><b>↗</b></button>`).join('');$$('[data-movie-cue]',cinema).forEach((b,j)=>b.onclick=()=>{seek(f.cues[j][0]);$$('[data-movie-cue]',cinema).forEach(n=>n.setAttribute('aria-pressed',String(n===b)));});};
   choose(cinema,'data-artemis-movie',setMovie);
   const jump=(i,t)=>{$(`[data-artemis-movie="${i}"]`,cinema).click();seek(t);cinema.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});};
   // Films share one player; the systems chapter retains the UI and architecture, not a second video module.
   $('[data-artemis-film]')?.closest('.depth-panel')?.remove();
   $('#chapter-1 .depth-inline img[src="assets/artemis-boss.webp"]')?.closest('figure')?.remove();
   artemisArt(jump);
  artemisChain();
 }

  function artemisArt(jump){
   const cast=node(heading('ART DIRECTION / CHARACTER & WORLD','让角色带着世界的痕迹。','<span class="comp-big">A.</span>')+`<div class="comp-cast-spread"><div class="comp-cast-stage">${svg(1200,735,`<defs><clipPath id="cast-world"><path d="M0 200H1200V500H0Z"/></clipPath><pattern id="cast-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#94a9ac" opacity=".12"/></pattern></defs><rect width="1200" height="735" fill="#101d2a"/><rect width="1200" height="735" fill="url(#cast-grid)"/><image href="${A}artemis-cg-tower.webp" x="0" y="200" width="1200" height="300" preserveAspectRatio="xMidYMid slice" clip-path="url(#cast-world)" opacity=".48"/><text x="36" y="87" class="comp-cast-title">ASTRONAUTS.</text><path d="M35 595H1165M418 135V670M796 135V670" fill="none" stroke="#9aaeb1" opacity=".45"/><image href="${A}artemis-hero.webp" x="70" y="105" width="350" height="510" preserveAspectRatio="xMidYMid meet"/><image href="${A}artemis-enemy-amber.webp" x="444" y="156" width="320" height="460" preserveAspectRatio="xMidYMid meet"/><image href="${A}artemis-enemy-indigo.webp" x="824" y="156" width="310" height="460" preserveAspectRatio="xMidYMid meet"/><text x="55" y="651" class="comp-svg-code">01 / EXPLORER</text><text x="450" y="651" class="comp-svg-code">02 / ENCOUNTER</text><text x="832" y="651" class="comp-svg-code">03 / ENCOUNTER</text><text x="55" y="686">蓝灰 · 琥珀 · 工程装备</text><text x="450" y="686">亮色 · 高反差 · 生物轮廓</text><text x="832" y="686">兜帽 · 冷色 · 细长比例</text>`,'探索者与两个遭遇角色的完整原设定，结合世界CG与造型分析')}</div><aside><span class="comp-code">SILHOUETTE / COLOR / CONTEXT</span><h4>同一个世界，<br>三种视觉重心。</h4><p>探索者的工程装备与琥珀面罩建立航天身份；遭遇角色通过明暗反差、轮廓与比例变化形成区分。</p><div class="comp-art-palette"><i style="--swatch:#273d61"></i><i style="--swatch:#8797a8"></i><i style="--swatch:#bd9764"></i><i style="--swatch:#d4d8bc"></i><span>从原画提炼的造型色彩</span></div><p>完整人物与废墟地景并置：角色不再是孤立贴图，而是观看世界的入口。</p><details><summary>查看角色设定页</summary><div class="comp-character-notes"><figure>${photo('artemis-character-heavy','重型角色原设定页')}<figcaption>重型角色 / 原设定</figcaption></figure><figure>${photo('artemis-character-machine','机械角色原设定页')}<figcaption>机械角色 / 原设定</figcaption></figure></div></details></aside></div>`+source('角色与场景取自原游戏美术目录及 F:/游戏PV/素材。此处为造型设定与美术编排，不是游戏实时画面。'),'comp-artemis-cast');chapter(1)?.prepend(cast);
   const story=[
    ['cg-fracture','裂变','月亮与碎石，占据同一个尺度。','圆形月面与向外散落的块面形成视觉张力，为世界的开场建立“大尺度”的观看。',17],
    ['cg-tower','重建','从碎片，转向垂直的秩序。','峭壁、塔楼与近景人物拉开比例，暖色光源使视线沿建筑向上移动。',46],
    ['cg-assembly','承诺','群像，成为叙事的声音。','人物面向中央光源，暗部前景包围亮部核心；字幕与动态文字接续画面的集体性。',51.5],
    ['cg-laboratory','异议','另一种选择，发生在边缘。','前景宇航员与实验空间形成多层构图，蓝白冷色转换前一段的暖色聚集。',72.5]
   ];
   const cg=node(heading('CG → CUTSCENE / VISUAL SEQUENCE','一幅画，如何进入一段叙事。','<span class="comp-big">04</span>')+`<div class="comp-cg-workspace"><figure class="comp-cg-stage"></figure><aside data-cg-reading aria-live="polite"></aside></div><div class="comp-cg-strip">${story.map(([key,title],i)=>`<button data-cg-scene="${i}" aria-pressed="${i===0}">${photo('artemis-'+key,title+'原CG')}<span><b>0${i+1}</b>${title}<i>↗</i></span></button>`).join('')}</div>`+source('四幅原 CG 依次对照过场 01；以下为构图与剪辑分析，不改写原剧情。点击影片入口查看画面如何与文字、运动和声音结合。'),'comp-artemis-cg');chapter(1)?.append(cg);
   choose(cg,'data-cg-scene',i=>{const [key,title,main,reading,t]=story[i];$('.comp-cg-stage',cg).innerHTML=svg(1100,650,`<defs><clipPath id="cg-photo"><rect x="32" y="28" width="1036" height="553"/></clipPath></defs><rect width="1100" height="650" fill="#101d2a"/><image href="${A}artemis-${key}.webp" x="32" y="28" width="1036" height="553" preserveAspectRatio="xMidYMid meet" clip-path="url(#cg-photo)"/><path d="M32 606H1068" stroke="#8caaae"/><text x="32" y="634" class="comp-svg-code">0${i+1} / ${title.toUpperCase()}</text><text x="1068" y="634" text-anchor="end" class="comp-svg-code">CG / ORIGINAL FRAME</text>`,title+'原CG与分镜编号');$('[data-cg-reading]',cg).innerHTML=`<span class="comp-code">0${i+1} / COMPOSITION STUDY</span><h4>${main}</h4><p>${reading}</p><div class="comp-cg-form">${i===0?'○ → ▰':i===1?'▱ → ↑':i===2?'◁ ● ▷':'▰ / ○'}</div><button data-cg-watch>在过场 01 中查看 ↗</button>`;$('[data-cg-watch]',cg).onclick=()=>jump(1,t);});
   const space=node(heading('SPACE / SOURCE COMPOSITION','把一张场景，读成空间关系。','<span class="comp-big">↗</span>')+`<div class="comp-scene-workspace"><div class="comp-scene-stage"></div><aside><span class="comp-code">PANORAMA / ARCHITECTURE / SCALE</span><h4>先看整体，<br>再进入局部。</h4><p>天空与月面建立环境尺度，低矮的平台组织地景，竖向塔楼成为识别锚点。用整体与局部的切换查看原场景的层级。</p>${tabs(['全景','建筑局部'],'data-world-scale')}<div class="comp-space-reading" aria-live="polite"></div></aside></div>`+source('源场景来自 F:/游戏PV/素材/背景.png、场景.png。SVG 视口只改变阅读范围，未新增建筑或将设定图标为实机场景。'),'comp-artemis-space');chapter(1)?.append(space);
   $('.comp-tabs',space).innerHTML+=`<button data-world-scale="2" aria-pressed="false">设定结构页</button>`;
   $('.comp-scene-workspace aside>p',space).textContent='星空与云层建立环境尺度，低矮的平台组织地景，竖向塔楼成为识别锚点。用整体与局部的切换查看原场景的层级。';
   choose(space,'data-world-scale',i=>{const stage=$('.comp-scene-stage',space);if(i===2)stage.innerHTML=svg(1800,1100,`<rect width="1800" height="1100" fill="#eae9d4"/><image href="${A}artemis-scene-blueprint.webp" width="1800" height="1100" preserveAspectRatio="xMidYMid meet"/>`,'原场景设定结构页');else{const view=i?'520 90 720 680':'0 0 1800 1100';stage.innerHTML=`<svg viewBox="${view}" role="img" aria-label="${i?'原建筑设定局部':'原场景设定全景与空间分析'}"><rect width="1800" height="1100" fill="#102b49"/><image href="${A}artemis-scene-background.webp" width="1800" height="724"/>${[[310,160,180,'01 / ATMOSPHERE','天幕 · 横向展开'],[850,325,760,'02 / LANDMARK','塔楼 · 垂直锚点'],[1100,647,1370,'03 / GROUND','地景 · 水平连接']].map(([x,y,end,code,title],j)=>`<circle cx="${x}" cy="${y}" r="18" fill="#f4ecbe"/><text x="${x}" y="${y+7}" text-anchor="middle" style="fill:#102b49;font-size:22px">${j+1}</text><path d="M${x} ${y+25}V${760+j*35}H${end}V880" stroke="#e5dcb3" opacity=".7" fill="none"/><text class="comp-space-map-label" x="${end}" y="933" style="fill:#e5dcb3;font-size:24px">${code}</text><text class="comp-space-map-label" x="${end}" y="990" style="fill:#f2efd8;font-size:37px">${title}</text>`).join('')}</svg>${i?'':`<div class="comp-space-mobile-key"><span><b>01</b>天幕<br>横向展开</span><span><b>02</b>塔楼<br>垂直锚点</span><span><b>03</b>地景<br>水平连接</span></div>`}`;}$('.comp-space-reading',space).textContent=['全景 / 横向的天幕与地景，衬托竖向建筑的识别性。','建筑局部 / 在原场景中观察塔楼、台阶与平台，不替换场景元素。','设定结构页 / 整体气氛与局部建筑、平台的原始设计关系。'][i];});
  }

 function artemisChain(){
  const slots=[{name:'根节点',cost:1,parent:-1,x:100,y:190},{name:'修饰分支 A',cost:2,parent:0,x:340,y:90},{name:'修饰分支 B',cost:4,parent:0,x:340,y:290},{name:'效果 A',cost:3,parent:1,x:585,y:90},{name:'效果 B',cost:2,parent:2,x:585,y:290}];
  const p=node(heading('BUILD / ENERGY IN THE CONNECTIONS','同一份能量，沿分支继续。','<span class="comp-big">1→2</span>')+`<div class="comp-chain-workspace"><div><div class="comp-chain-key"><span>○ 等待</span><span>● 已执行</span><span>× 分支停止</span></div><div class="comp-chain-graph"></div><div class="comp-chain-status" role="status"></div></div><aside><span class="comp-code">TRIGGER TREE / 规则演示</span><h4>先触发自己，<br>再交给下一层。</h4><label>初始能量 <output data-chain-energy>8</output><input type="range" min="0" max="12" value="8" step="1" data-chain-budget aria-label="构筑示例初始能量"></label><p>检查耗能，执行效果，再等待下一次推进。同一父节点的两个子分支分别接收数据副本。</p><div class="comp-chain-controls"><button data-chain-start>启动根节点</button><button data-chain-next disabled>推进下一层</button><button data-chain-reset>重置</button></div><dl><dt>连接</dt><dd>出口边 → 相邻入口边</dd><dt>数据</dt><dd>currentEnergy / energyCost</dd><dt>传播</dt><dd>outgoingModifier.Clone()</dd></dl></aside></div>`+source('依据 H:/final 中 HexSystem、BackpackSlot 与 ItemComponent 重绘。五节点和耗能用于讲解规则；原游戏用左键启动、右键推进。'),'comp-artemis-chain');chapter(3)?.prepend(p);
  let stage=-1,records=[];const budget=$('[data-chain-budget]',p),start=$('[data-chain-start]',p),next=$('[data-chain-next]',p);
  const hex=(x,y)=>`${x-72},${y} ${x-36},${y-62} ${x+36},${y-62} ${x+72},${y} ${x+36},${y+62} ${x-36},${y+62}`;
  function paint(){
   const wires=slots.slice(1).map((s,j)=>{const parent=slots[s.parent],done=records[j+1]?.state==='done',blocked=records[j+1]?.state==='blocked';return `<path d="M${parent.x+72} ${parent.y}L${s.x-72} ${s.y}" class="comp-chain-wire ${done?'done':''} ${blocked?'blocked':''}"/>`;}).join('');
   $('.comp-chain-graph',p).innerHTML=svg(700,385,`${wires}<text x="210" y="184" text-anchor="middle" class="comp-svg-code">CLONE</text>${slots.map((s,i)=>{const r=records[i],state=r?.state||'waiting',label=state==='done'?`余能 ${r.after}`:state==='blocked'?'× 能量不足':r?.state==='skipped'?'前序停止':`耗能 ${s.cost}`;return `<g class="comp-chain-node ${state}"><polygon points="${hex(s.x,s.y)}"/><text x="${s.x}" y="${s.y-22}" text-anchor="middle" class="comp-svg-code">${i===0?'ROOT':`NODE 0${i+1}`}</text><text x="${s.x}" y="${s.y+5}" text-anchor="middle" class="comp-svg-title">${s.name}</text><text x="${s.x}" y="${s.y+32}" text-anchor="middle">${label}</text></g>`;}).join('')}`,'五节点构筑树，展示分支独立复制能量与分层触发');
   const active=records.filter(x=>x?.state==='done').length,stopped=records.filter(x=>x?.state==='blocked').length;
   $('.comp-chain-status',p).innerHTML=stage<0?'<b>等待启动</b><span>调整能量，观察两个分支如何继续。</span>':`<b>${stage===2||next.disabled?'本轮结束':`第 ${stage+1} 层已执行`}</b><span>${active} 个节点执行 · ${stopped} 个分支停止${stage<2&&!next.disabled?' · 等待推进下一层':''}</span>`;
  }
  function reset(){stage=-1;records=[];next.disabled=true;start.disabled=false;paint();}
  function run(indices){indices.forEach(i=>{const s=slots[i],parent=s.parent<0?null:records[s.parent];if(parent&&parent.state!=='done'){records[i]={state:'skipped'};return;}const energy=parent?parent.after:+budget.value;records[i]=energy<s.cost?{state:'blocked',before:energy}:{state:'done',before:energy,after:energy-s.cost};});}
  start.onclick=()=>{stage=0;records=[];run([0]);start.disabled=true;next.disabled=records[0].state!=='done';paint();};
  next.onclick=()=>{stage++;run(stage===1?[1,2]:[3,4]);next.disabled=stage>=2||![1,2].some(i=>records[i]?.state==='done');paint();};
  $('[data-chain-reset]',p).onclick=reset;budget.oninput=()=>{$('[data-chain-energy]',p).textContent=budget.value;reset();};reset();
 }

 function bronze(){
  const block=node(heading('NARRATIVE TOPOLOGY / 5 + 1 + 4','同一段旅程，两条身份线。','<span class="comp-big">↔</span>')+`<div class="comp-plot-scroll"><div class="comp-bronze-map"></div></div><div class="comp-story-reading" aria-live="polite"></div>`+tabs(['01—05 / 铺陈','06 / 断裂','07—10 / 整合'],'data-story-act')+source('依据最终汇报与十集成片整理；路径位置用于区分叙事线，不编码情绪强度、镜头时长或观众反应。'),'comp-bronze-analysis');
  const stills=$('.bronze-story-stills');if(stills){const wrap=document.createElement('div');wrap.className='comp-bronze-spread';stills.before(wrap);wrap.append(block,stills);}
  $('.comp-bronze-map',block).innerHTML=svg(680,350,`<rect x="348" y="28" width="54" height="256" fill="#cf3828" opacity=".12"/><path d="M30 88H306L375 151 445 106 582 174 650 130" class="comp-story-path"/><path d="M30 248H306L375 177 445 250 582 174 650 215" class="comp-story-path secondary"/><text x="30" y="51">星辰 / 寻亲</text><text x="30" y="288">阿鸮 / 寻名</text>${Array.from({length:10},(_,i)=>`<text x="${30+i*69}" y="329" text-anchor="middle">${String(i+1).padStart(2,'0')}</text>`).join('')}<circle cx="375" cy="164" r="23" fill="#cf3828"/><text x="375" y="170" text-anchor="middle" fill="white">06</text><circle cx="582" cy="174" r="25" fill="#cf3828"/><text x="582" y="180" text-anchor="middle" fill="white">09</text><text x="360" y="29">断裂</text><text x="533" y="121">三方融合</text>`,'星辰与阿鸮的双线叙事结构，第6集断裂，第9集融合');
  const entries=[['器物作为记忆入口','竞技让新器灵进入故事；识别器形的过程，也让身份线索逐渐累积。'],['改变推进规则','第六集不再以获得下一场胜利推进：阿鸮陨落，追寻从行动任务转为身份问题。'],['让视觉锚点完成回收','簪花与吊坠跨越造型；第九集的融合不是新增孤立角色，而是前两条线和记忆的交汇。']];choose(block,'data-story-act',i=>{$('.comp-story-reading',block).innerHTML=`<h4>${entries[i][0]}</h4><p>${entries[i][1]}</p>`;});
 }

 function afterglow(){
  const p=node(heading('TYPE AS ENVIRONMENT / ENCODING ANATOMY','信号不是背景，而是字形的条件。','<span class="comp-big">環</span>')+`<div class="comp-afterglow-lab"><div class="comp-glyph-canvas" data-glyph-canvas></div><aside><span class="comp-code">FORM STUDY / 原理示意</span><h4>密度、振幅、尺度、方向。</h4><p>在同一径向骨架中分别观察四种变化。这里使用无单位设计参数；原始样本与 V4 运行结果在下方独立呈现。</p>${[['density','密度 / 人流通道',55],['amplitude','振幅 / 噪声通道',45],['size','尺度 / PM2.5 通道',40],['wind','方向 / 风通道',60]].map(x=>`<label>${x[1]}<input type="range" min="0" max="100" value="${x[2]}" data-glyph="${x[0]}" aria-label="${x[1]}"></label>`).join('')}</aside></div><div class="comp-glyph-breakdown">${[['01','环形骨架','一个共同中心'],['02','径向序列','密度与间隔'],['03','文字尺度','字号与边界'],['04','方向场','旋转与倾斜']].map(x=>`<article><b>${x[0]}</b><h4>${x[1]}</h4><p>${x[2]}</p></article>`).join('')}</div>`+source('根据原编码逻辑重绘的可操作形态拆解，不冒充原站实时监測；实际 V4 代码、19 个时间点与网页录屏分别保留。'),'comp-afterglow-anatomy');replace(1,p);
  function draw(){const values=Object.fromEntries($$('[data-glyph]',p).map(e=>[e.dataset.glyph,+e.value])),count=18+Math.round(values.density*.35),angle=values.wind/100*100,fontsize=9+values.size*.15;let shapes='';for(let i=0;i<count;i++){const a=i/count*360+angle,len=135+Math.sin(i*1.7)*values.amplitude*.9;shapes+=`<g transform="rotate(${a} 340 340)"><path d="M340 220V${220-len}" stroke="currentColor" opacity=".3"/><text x="340" y="${205-len/2}" text-anchor="middle" transform="rotate(90 340 ${205-len/2})" style="font-size:${fontsize}px">AFTERGLOW</text></g>`;}
   $('[data-glyph-canvas]',p).innerHTML=svg(680,680,`<circle cx="340" cy="340" r="275" class="comp-glyph-orbit"/><circle cx="340" cy="340" r="120" class="comp-glyph-orbit"/><path d="M20 340H660M340 20V660" class="comp-hairline"/>${shapes}<circle cx="340" cy="340" r="87" fill="#141b19"/><text x="340" y="340" text-anchor="middle" class="comp-svg-title">余晖环</text><text x="340" y="372" text-anchor="middle">FORM / STUDY</text>`,'四个参数控制的径向文字形态示意');}
  $$('[data-glyph]',p).forEach(e=>e.oninput=draw);draw();
 }
})();
