(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const dialog=$('#jw-lightbox');
function bindImages(root=document){$$('[data-jw-image]',root).forEach(b=>b.addEventListener('click',()=>{$('img',dialog).src=b.dataset.jwImage;$('img',dialog).alt=b.dataset.caption||$('img',b)?.alt||'镜外实机图';$('p',dialog).textContent=b.dataset.caption||'';dialog.showModal();}));}$('.jw-close',dialog).addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
const rescue={
cart:{title:'接住落灯，留下撞痕。',image:'assets/jingwai/chandelier-v138.webp',caption:'025吊灯与受力结构 / Unity v1.3.8',intro:'把餐车推到吊灯下，接住落下的灯。艾达避开危险，灯座却撞坏了；马丁仍要处理吊索。',steps:[['025 / 救援','推车接灯，排演确认，再拍下艾达获救的画面。'],['留下的证据','受损灯座与撞痕。照片记录了灯落在哪里、怎样被接住。'],['07 / 检修','拍撞痕，读刻线，按这次损伤调整器械与光路。']]},
cable:{title:'把索接回去，让马丁松手。',image:'assets/jingwai/family-v133.webp',caption:'钩索路线 / 三人合影 · v1.3.3留存帧',intro:'拍清断索和吊环，用钩索接回受力点。灯没有摔下，马丁终于能走到家人身边。艾达想要的合影，这时才拍得成。',steps:[['025 / 救援','对准挂点接索，排演后把三个人一起拍进画面。'],['留下的证据','同一次放映中的三人合影。只拍到艾达也能救人，完整合影另有用途。'],['07 / 检修','用写着三个人名字的镂空框，对齐照片里的马丁、艾达与米娅，拍下校准片；合影不完整时，改用公共片继续。']]},
brace:{title:'从下面托住，记下锁位。',image:'assets/jingwai/brace-v133.webp',caption:'撑杆路线 / 低位握轮与支撑 · v1.3.3留存帧',intro:'把撑杆放到吊灯下，转动低位握轮，让托头贴住灯底，再锁住。艾达可以离开，马丁仍抓着原索。灯被临时撑住了，吊索还没有修好。',steps:[['025 / 救援','放稳撑杆，伸长到接触灯底，锁止后排演。'],['留下的证据','两段伸长行程与三节锁位。它们记录了这次支撑怎样成立。'],['07 / 检修','对照锁位照片，调节检修架的两段套管。铜环对齐后合总锁，抬起挡光闸。']]}
};
const buttons=$$('[data-jw-rescue]'),panel=$('#jw-rescue-panel');function select(key){const d=rescue[key];if(!d)return;buttons.forEach(b=>{const on=b.dataset.jwRescue===key;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;});panel.setAttribute('aria-labelledby','jw-rescue-'+key);panel.innerHTML='<figure><button data-jw-image="'+esc(d.image)+'" data-caption="'+esc(d.caption)+'" aria-label="放大该路线的真实图片"><img src="'+esc(d.image)+'" alt="'+esc(d.caption)+'" loading="lazy"></button><figcaption>'+esc(d.caption)+'</figcaption></figure><div><span class="jw-kicker">IN THE FILM → BACK ON THE STREET</span><h3>'+esc(d.title)+'</h3><p>'+esc(d.intro)+'</p><dl>'+d.steps.map(s=>'<div><dt>'+esc(s[0])+'</dt><dd>'+esc(s[1])+'</dd></div>').join('')+'</dl></div>';bindImages(panel);}
buttons.forEach((b,i)=>{b.addEventListener('click',()=>select(b.dataset.jwRescue));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[j].focus();select(buttons[j].dataset.jwRescue);});});bindImages();select('cart');
const media=window.JINGWAI_MEDIA||{};const valid=s=>{if(typeof s!=='string'||!s.trim())return '';if(/^https?:\/\//i.test(s)){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}return !/^(?:[a-z]+:|\/\/|\\)/i.test(s)&&!s.split('/').includes('..')?s:'';};const file=valid(media.recordingFile),url=valid(media.recordingUrl);if(file||url){const host=$('[data-jw-recording]');host.innerHTML=(file?'<figure><video src="'+esc(file)+'" poster="assets/jingwai/chandelier-v138.webp" controls playsinline preload="metadata" aria-label="'+esc(media.title||'镜外原生实机演示')+'"></video><figcaption>'+esc(media.title||'镜外原生实机演示')+'</figcaption></figure>':'<figure><img src="assets/jingwai/chandelier-v138.webp" alt="镜外原生实机演示预览" width="1600" height="900"><figcaption>'+esc(media.title||'镜外原生实机演示')+'</figcaption></figure>')+(url?'<a class="jw-link" href="'+esc(url)+'" target="_blank" rel="noopener">打开真实实机演示 <span>↗</span></a>':'')+'<p class="jw-media-state" role="status">'+esc(media.note||'真实游戏运行记录；请以视频说明中的操作和剪辑范围为准。')+'</p>';const v=$('video',host);v?.addEventListener('error',()=>{$('.jw-media-state',host).textContent='视频未能载入，请刷新或使用外部录屏入口；当前实机截图仍可查看。';});}
})();
