(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const dialog=$('#jw-lightbox');
function bindImages(root=document){$$('[data-jw-image]',root).forEach(b=>b.addEventListener('click',()=>{$('img',dialog).src=b.dataset.jwImage;$('img',dialog).alt=b.dataset.caption||$('img',b)?.alt||'镜外实机图';$('p',dialog).textContent=b.dataset.caption||'';dialog.showModal();}));}$('.jw-close',dialog).addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
const rescue={
cart:{title:'接住吊灯，再处理撞坏的东西。',image:'assets/jingwai/chandelier-v138.webp',caption:'025吊灯与高处结构 / v1.3.8真实引擎帧，图中不是餐车成功后的结果',intro:'把餐车推到吊灯下，让它接住坠落的灯。艾达避开了危险，灯座却留下实际撞痕。',steps:[['电影中','移动餐车，排演确认吊灯落到车上，补拍本次结果。'],['留下什么','受损灯座与撞痕照片。救下人的办法，也把损伤带进了后续调查。'],['07号继续','观察撞痕参考，实际转动器械、调整光路，再退闩开盖拍图。']]},
cable:{title:'接回吊索，腾出一家人合影的手。',image:'assets/jingwai/family-v133.webp',caption:'钩索路线三人照片 / v1.3.3历史正式摄影；不冒充v1.3.8新拍图',intro:'先拍清断索和吊环，再用青铜钩索真实接回受力点。马丁不用一直扶索，玩家可以拍到一家三人的同源合影。',steps:[['电影中','确认断索与吊环，持钩对准真实挂点接索，再排演与补拍。'],['留下什么','一家三人的真实合影。照片是否完整，继续影响后面的个人或公共校准依据。'],['07号继续','带着同源合影，让镂空人名框逐一对上三个人，取得校准片，再接回光路。']]},
brace:{title:'先从下面托稳，记住撑住它的行程。',image:'assets/jingwai/brace-v133.webp',caption:'低位握轮与撑杆操作 / v1.3.3真实历史运行帧',intro:'把撑杆放到吊灯下，操作低位握轮，让三节杆伸出；托头接触灯底后锁住。艾达获救，马丁仍在维持原索，暂时没有空闲合影。',steps:[['电影中','拿起、放稳、伸长、接触灯底、锁住，再排演确认实际支撑成立。'],['留下什么','本次两段行程和三节锁位的见证。临时托住与完整修复，是两种不同的状态。'],['07号继续','读取尺和白线，重新调好两段检修套管；总锁正确后才抬起挡光闸，继续调光。']]}
};
const buttons=$$('[data-jw-rescue]'),panel=$('#jw-rescue-panel');function select(key){const d=rescue[key];if(!d)return;buttons.forEach(b=>{const on=b.dataset.jwRescue===key;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;});panel.setAttribute('aria-labelledby','jw-rescue-'+key);panel.innerHTML='<figure><button data-jw-image="'+esc(d.image)+'" data-caption="'+esc(d.caption)+'" aria-label="放大该路线的真实图片"><img src="'+esc(d.image)+'" alt="'+esc(d.caption)+'" loading="lazy"></button><figcaption>'+esc(d.caption)+'</figcaption></figure><div><span class="jw-kicker">IN THE FILM → BACK ON THE STREET</span><h3>'+esc(d.title)+'</h3><p>'+esc(d.intro)+'</p><dl>'+d.steps.map(s=>'<div><dt>'+esc(s[0])+'</dt><dd>'+esc(s[1])+'</dd></div>').join('')+'</dl></div>';bindImages(panel);}
buttons.forEach((b,i)=>{b.addEventListener('click',()=>select(b.dataset.jwRescue));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[j].focus();select(buttons[j].dataset.jwRescue);});});bindImages();select('cart');
const media=window.JINGWAI_MEDIA||{};const valid=s=>{if(typeof s!=='string'||!s.trim())return '';if(/^https?:\/\//i.test(s)){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}return !/^(?:[a-z]+:|\/\/|\\)/i.test(s)&&!s.split('/').includes('..')?s:'';};const file=valid(media.recordingFile),url=valid(media.recordingUrl);if(file||url){const host=$('[data-jw-recording]');host.innerHTML=(file?'<figure><video src="'+esc(file)+'" poster="assets/jingwai/chandelier-v138.webp" controls playsinline preload="metadata" aria-label="'+esc(media.title||'镜外原生实机演示')+'"></video><figcaption>'+esc(media.title||'镜外原生实机演示')+'</figcaption></figure>':'<figure><img src="assets/jingwai/chandelier-v138.webp" alt="镜外原生实机演示预览" width="1600" height="900"><figcaption>'+esc(media.title||'镜外原生实机演示')+'</figcaption></figure>')+(url?'<a class="jw-link" href="'+esc(url)+'" target="_blank" rel="noopener">打开真实实机演示 <span>↗</span></a>':'')+'<p class="jw-media-state" role="status">'+esc(media.note||'真实游戏运行记录；请以视频说明中的操作和剪辑范围为准。')+'</p>';const v=$('video',host);v?.addEventListener('error',()=>{$('.jw-media-state',host).textContent='视频未能载入，请刷新或使用外部录屏入口；当前实机截图仍可查看。';});}
const pdf=valid(media.applicationPdf);if(pdf){$('[data-jw-pdf]').innerHTML='<a class="jw-link" href="'+esc(pdf)+'" target="_blank" rel="noopener">查看本项目投递说明 <span>↗ PDF</span></a>';}
})();
