/* Insert Jingwai after the garden; synchronize the existing labels and book pagination without re-running artwork layers. */
(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],p=window.PORTFOLIO?.projects.find(p=>p.id==='jingwai'),grid=$('#project-grid');if(!p||!grid||$('#folio-jingwai'))return;
const plate=document.createElement('article');plate.className='book-spread project-plate jingwai-home-plate is-read';plate.id='folio-jingwai';plate.dataset.project='jingwai';plate.innerHTML='<div class="plate-colour" aria-hidden="true"></div><p class="book-running">11 / 独立游戏 · AI 协作制作 <span>2026</span></p><p class="jw-home-key">放映员 / 摄影解谜 / UNITY 首章</p><h3 class="plate-title"><a href="jingwai.html">镜外<span>。</span></a></h3><div class="plate-copy"><h4>改一段电影，<br>回到现实看它留下什么。</h4><p>走进电影、救下艾达，再把同一封原信交到米娅手里。餐车、钩索和撑杆留下不同线索，送信的办法继续改变后面的调查。</p><p class="plate-role">独立策划与视觉把关 · AI 协作实现<br>Unity Windows 首章 Demo · v1.3.8</p><a class="plate-link" href="jingwai.html" aria-label="查看完整项目：镜外"><span class="finish-cta-label">查看完整项目</span><span class="finish-cta-icon">↗</span></a></div><figure class="jw-home-main"><a href="jingwai.html"><img src="assets/jingwai/hotel-v138.webp" alt="镜外025酒店大厅，Unity v1.3.8实际运行画面" width="1600" height="900" loading="lazy"></a><figcaption>025 / 23:17 之前 · Unity v1.3.8 实机帧</figcaption></figure><figure class="jw-home-inset"><a href="jingwai.html#chapter-3"><img src="assets/jingwai/workbench-v138.webp" alt="镜外现实07号检修器械，Unity v1.3.8实机帧" width="1600" height="900" loading="lazy"></a><figcaption>改变以后，继续查证。</figcaption></figure><nav class="jw-home-mechanisms" aria-label="镜外章节入口"><a href="jingwai.html#chapter-2"><b>01</b>三种救援<span>办法留下不同线索 ↗</span></a><a href="jingwai.html#chapter-3"><b>02</b>原信送递<span>顺序改变收信位置 ↗</span></a><a href="jingwai.html#chapter-4"><b>03</b>AI 协作<span>把感觉拆成制作标准 ↗</span></a></nav><div class="spread-footer"><span>AFTERIMAGE / DESIGN · BUILD · PLAY</span><span>24—25</span></div>';
const gardenPlate=$('#folio-garden');if(gardenPlate)gardenPlate.after(plate);else grid.append(plate);const index=$('.book-project-index');if(index){const a=document.createElement('a');a.href='#folio-jingwai';a.dataset.indexProject='jingwai';a.innerHTML='<span>11</span>镜外';const gardenIndex=$('[data-index-project="garden"]',index);if(gardenIndex)gardenIndex.after(a);else index.append(a);}const title=$('.book-index h2');if(title)title.innerHTML='Selected work<span> / 11</span>';const coverCount=$('.reference-home-head span:last-child');if(coverCount)coverCount.textContent='SELECTED WORK / 11 PROJECTS';
window.PORTFOLIO.projects.forEach((x,i)=>{const e=$('#folio-'+x.id);if(!e)return;const running=$('.book-running',e);if(running?.firstChild?.nodeType===3)running.firstChild.textContent=running.firstChild.textContent.replace(/^\d{2}(?=\s*\/)/,x.number);$$('.plate-folio,.reference-project-number',e).forEach(n=>n.textContent=x.number);const pages=$('.spread-footer span:last-child',e);if(pages){const start=4+i*2;pages.textContent=String(start).padStart(2,'0')+'—'+String(start+1).padStart(2,'0');}const idx=$('[data-index-project="'+x.id+'"] span');if(idx)idx.textContent=x.number;const link=$('.plate-link',e);if(link?.firstChild?.nodeType===3)link.firstChild.textContent=link.firstChild.textContent.replace(/查看项目\s*\/\s*\d{2}/,'查看项目 / '+x.number);});const nProjects=window.PORTFOLIO.projects.length,researchStart=4+nProjects*2;const researchPages=$('#research .spread-footer span:last-child');if(researchPages)researchPages.textContent=String(researchStart).padStart(2,'0')+'—'+String(researchStart+1).padStart(2,'0');const contactPage=$('#contact .spread-footer span:last-child');if(contactPage)contactPage.textContent=String(researchStart+2).padStart(2,'0');
// The original filter closes over ten artwork records. This full-list filter runs only on the homepage controls.
let route='all';const groups={product:['rallylens','privacy-city','tennisatom','growth-compass','looplab'],game:['artemis','garden','jingwai'],ai:['privacy-city','bronze','tennisatom','growth-compass','jingwai'],data:['baseball','afterglow','rallylens']};
const filter=()=>{const q=$('#work-query').value.trim().toLowerCase();let n=0;$$('.project-plate').forEach(e=>{const x=window.PORTFOLIO.projects.find(x=>x.id===e.dataset.project);if(!x)return;e.hidden=(route!=='all'&&!groups[route]?.includes(x.id))||!([x.name,x.cn,x.summary,x.label,...x.tools,...x.responsibilities].join(' ').toLowerCase().includes(q));const link=$('[data-index-project="'+x.id+'"]');if(link)link.hidden=e.hidden;if(!e.hidden)n++;});$('#filter-status').textContent='显示 '+n+' 个项目';$('#work-empty').hidden=n>0;$$('[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.route===route)));};
$$('[data-route]').forEach(b=>b.addEventListener('click',e=>{e.stopImmediatePropagation();route=b.dataset.route;filter();},true));$('#work-query')?.addEventListener('input',e=>{e.stopImmediatePropagation();filter();},true);$('#work-clear')?.addEventListener('click',e=>{e.stopImmediatePropagation();$('#work-query').value='';filter();$('#work-query').focus();},true);filter();
})();
