/* Editable case-specific diagrams. All numbers are source records, not decorative telemetry. */
(() => {
 'use strict';
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const el=(tag,cls,html='')=>{const n=document.createElement(tag);n.className=cls;n.innerHTML=html;return n;};
 const id=document.body.dataset.project,projects=window.PORTFOLIO.projects;
 document.body.classList.add('depth-edition');
 function reserveImages(root=document){$$('img[src^="assets/"]',root).forEach(img=>{const d=window.FOLIO_IMAGE_SIZES?.[img.getAttribute('src')];if(d){img.width=d[0];img.height=d[1];}});}
 reserveImages();new MutationObserver(()=>reserveImages()).observe(document.body,{childList:true,subtree:true});
 function panel(code,title,num,body,note='',cls=''){return el('section','depth-panel '+cls,`<header><div><span class="depth-code">${code}</span><h3>${title}</h3></div><span aria-hidden="true">${num}</span></header>${body}${note?`<p class="depth-source">${note}</p>`:''}`);}
 function image(key,caption){return `<figure><button data-book-art="${key}" data-caption="${esc(caption)}" aria-label="放大：${esc(caption)}"><img src="assets/${key}.webp" alt="${esc(caption)}" loading="lazy"></button><figcaption>${caption}</figcaption></figure>`;}
 function visual(n){return $(`#chapter-${n} .chapter-visuals`);}
 function add(n,node,replace=false){const v=visual(n);if(v){if(replace)v.replaceChildren(node);else v.append(node);}}
 function select(root,attr,fn){const bs=$$(`[${attr}]`,root);function go(i){bs.forEach((b,j)=>b.setAttribute('aria-pressed',String(j===i)));fn(i);}
  bs.forEach((b,i)=>{b.addEventListener('click',()=>go(i));b.addEventListener('keydown',e=>{const keys=['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'];if(!keys.includes(e.key))return;e.preventDefault();e.stopPropagation();const j=e.key==='Home'?0:e.key==='End'?bs.length-1:(i+(e.key==='ArrowRight'||e.key==='ArrowDown'?1:-1)+bs.length)%bs.length;bs[j].focus();go(j);});});if(bs.length)go(0);
 }
 function bindDiagram(root,nodeAttr,buttonAttr){$$(`[${nodeAttr}]`,root).forEach(n=>{const b=$(`[${buttonAttr}="${n.getAttribute(nodeAttr)}"]`,root);n.closest('svg').setAttribute('role','group');n.setAttribute('role','button');n.setAttribute('tabindex','0');n.setAttribute('aria-label','查看：'+b.innerText.replace(/\s+/g,' '));n.addEventListener('click',()=>b.click());n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click();}});});}
 function flow(code,title,items,note,cls=''){
  const p=panel(code,title,String(items.length).padStart(2,'0'),`<div class="depth-flow" role="group" aria-label="${esc(title)}">${items.map((x,i)=>`<button data-depth-flow="${i}" aria-pressed="${i===0}"><span class="depth-code">${String(i+1).padStart(2,'0')} / ${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div><div class="depth-flow-detail" aria-live="polite"></div>`,note,cls);
  if(code.startsWith('UNITY')||code.startsWith('SYSTEM')||code.startsWith('NUMPY')||code.startsWith('DPE /')){
   const hub=code.startsWith('DPE /'),tensor=code.startsWith('NUMPY'),cols=tensor?4:3,w=tensor?1050:990,h=hub?440:tensor?235:370;
   const points=items.map((x,i)=>hub?[495+Math.cos(-Math.PI/2+i*Math.PI*2/items.length)*355,215+Math.sin(-Math.PI/2+i*Math.PI*2/items.length)*165]:[70+(i%cols)*(tensor?245:300),55+Math.floor(i/cols)*165]);
   const edges=hub?items.map((_,i)=>[-1,i]):code.startsWith('UNITY')?[[0,1],[1,2],[1,3],[3,5],[4,5],[2,5]]:items.slice(1).map((_,i)=>[i,i+1]);
   const graph=el('div','depth-module-map',`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}关系图"><title>${esc(title)}</title><defs><marker id="${code.startsWith('UNITY')?'unity':code.startsWith('SYSTEM')?'privacy':tensor?'tensor':'dpe'}-edge" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5 0 10" fill="currentColor"/></marker></defs>${hub?'<circle cx="495" cy="215" r="54" class="map-hub"/><text x="495" y="213" text-anchor="middle" class="hub-text">DPE</text><text x="495" y="235" text-anchor="middle" class="hub-small">共同检查单元</text>':''}${edges.map(([a,b],j)=>{const s=a<0?[495,215]:points[a],t=points[b];let d;if(hub){d=`M495 215L${t[0]} ${t[1]}`;}else if(Math.floor(a/cols)===Math.floor(b/cols)&&b-a>1){d=`M${s[0]+95} ${s[1]+93}V${s[1]+122}H${t[0]+95}V${t[1]+96}`;}else if(Math.floor(a/cols)===Math.floor(b/cols)){d=`M${s[0]+190} ${s[1]+46}H${t[0]-8}`;}else{d=`M${s[0]+95} ${s[1]+93}V${t[1]-22}H${t[0]+95}V${t[1]-5}`;}return `<path data-map-edge="${j}" class="map-edge" d="${d}" ${hub?'':`marker-end="url(#${code.startsWith('UNITY')?'unity':code.startsWith('SYSTEM')?'privacy':tensor?'tensor':'dpe'}-edge)"`}/>`;}).join('')}${items.map((x,i)=>{const q=points[i],x0=hub?q[0]-91:q[0],y0=hub?q[1]-32:q[1];return `<g class="map-node" data-map-node="${i}"><rect x="${x0}" y="${y0}" width="${hub?182:190}" height="${hub?64:92}"/><text class="map-key" x="${x0+13}" y="${y0+20}">${String(i+1).padStart(2,'0')} / ${esc(x[0].split(' / ').at(-1))}</text><text class="map-label" x="${x0+13}" y="${y0+(hub?45:54)}">${esc(x[1])}</text>${hub?'':`<text class="map-small" x="${x0+13}" y="${y0+76}">${esc(x[2])}</text>`}</g>`;}).join('')}</svg><p>${hub?'七种证据汇入同一检查单元，不把解释层当成事实层。':tensor?'前向：输入 → 表征 → 概率　/　训练时：误差沿图反向传播':'箭头表示信息或状态依赖。选择下方模块，查看对应职责。'}</p>`);
   if(hub)$$('[data-map-edge]',graph).forEach((line,j)=>{const q=points[j],dx=q[0]-495,dy=q[1]-215,len=Math.hypot(dx,dy);line.setAttribute('d',`M${495+dx/len*55} ${215+dy/len*55}L${q[0]} ${q[1]}`);});
   $('.depth-flow',p).before(graph);p._mapEdges=edges;
  }
  select(p,'data-depth-flow',i=>{$('.depth-flow-detail',p).innerHTML=`<strong>${String(i+1).padStart(2,'0')}</strong><div><h4>${items[i][1]}</h4><p>${items[i][3]}</p></div>`;$$('[data-map-node]',p).forEach((n,j)=>{n.classList.toggle('active',i===j);n.setAttribute('aria-pressed',String(i===j));});$$('[data-map-edge]',p).forEach((n,j)=>n.classList.toggle('active',p._mapEdges[j].includes(i)));});bindDiagram(p,'data-map-node','data-depth-flow');return p;
 }
 function embed(title,url,poster,note,external){
  const p=panel('ORIGINAL WEB / 原项目网页',title,'↗',`<div class="depth-embed-bar"><span>原项目完整交互 · 独立滚动</span><a href="${url}" target="_blank" rel="noopener">全屏打开本地原型 ↗</a>${external?`<a href="${external}" target="_blank" rel="noopener">访问原网站 ↗</a>`:''}<button data-load-original>载入原网页</button></div><div class="depth-embed"><button data-load-original class="depth-web-cover" style="width:100%;border:0;background:#151d25;padding:0;cursor:pointer"><img src="assets/${poster}.webp" alt="原网页预览，点击载入完整交互" style="width:100%;display:block"><span style="display:block;padding:20px;color:white">点击进入原项目交互 ↗</span></button></div>`,note);
  $$('[data-load-original]',p).forEach(b=>b.addEventListener('click',()=>{$('.depth-embed',p).innerHTML=`<iframe src="${url}" title="${esc(title)}" loading="eager" allow="fullscreen" allowfullscreen></iframe>`;$('[data-load-original]',p)?.remove();}));return p;
 }
 // Remove the repeated appendix, not the user's original files.
 $('#design-assets')?.remove();
 $$('a[href="#design-assets"]').forEach(a=>a.remove());
 const ix=projects.findIndex(p=>p.id===id),next=projects[(ix+1)%projects.length];
 if(ix>=0&&$('.case-next')){const n=$('.case-next');n.href='case.html?project='+next.id;n.innerHTML=`<div><p>NEXT PROJECT / ${next.number}</p><h2>${esc(next.name)} — ${esc(next.cn)}</h2></div><span aria-hidden="true">↗</span>`;}
 if($('.notebook-footer')&&id){$('.notebook-footer').before(el('div','depth-contact','<span>联系卞文璟</span><a href="tel:18912920069">18912920069</a><a href="mailto:2352970@tongji.edu.cn">2352970@tongji.edu.cn ↗</a>'));}
 if(id==='looplab')$('.case-reflection')?.remove();
 const homeLoop=$('#folio-looplab .plate-copy>p:nth-of-type(2)');if(homeLoop)homeLoop.textContent='材料交换、制作预约、小量团购、项目档案与校园取件地图。把五类相邻产品的机制转成适合校园的获取、制作与交接流程。';
 if(!id)return;

 if(id==='rallylens'){
  const episodes=[['G01_01',9,0,'自由练习','接球方如何理解“照顾”仍需另看陈述。','P01 + P02','未链接'],['G01_02',16,2,'角色练习','共享目标，并不意味着双方采用同一套喂球计划。','P01 + P02','C01 · 阶段级'],['G01_03',6,1,'计分阶段','计分改变了双方描述这段练习的方式。','P01 + P02','C01 · 阶段级'],['G01_04',13,1,'角色练习','一次合适的回球，也可以是跨回合练习的一部分。','P01 + P02','未链接'],['G03_01',13,1,'自由练习','从动作推测的目标，未必是参与者持有的目标。','P05 + P06','未链接'],['G03_02',16,0,'角色练习','中场喂球、放松和练习目标被不同地理解。','P05 + P06','C03 · 另一阶段'],['G03_03',13,0,'角色练习','两人把“共同练习”定位在不同的环节。','P05 + P06','C03 · 阶段级'],['G03_04',15,1,'角色练习','网前练习并不以回合越长越好为标准。','P06','未链接'],['G07_01',25,3,'自由练习','长回合看起来稳定，但不等同于明确的练习目标。','P09 + P10','C02 · 阶段级'],['G07_02',8,1,'角色练习','同一片段被理解为决策压力，也被理解为热身。','P09 + P10','C04 / C07 · 阶段级'],['G07_03',14,1,'角色练习','支持是否成立，取决于来球条件。','P09 + P10','C03 / C07 · 阶段级'],['G07_04',12,0,'计分阶段','进入计分后，双方对练习的解释再次变化。','P09 + P10','C02 · 阶段级']];
  const p=panel('DPE ATLAS / 论文片段记录','同一段练习，保留多种证据。','12',`<div class="depth-two"><div class="depth-rows"><div class="depth-axis"><span>0</span><span>事件数 / 25</span></div><div role="group" aria-label="选择研究片段">${episodes.map((e,i)=>`<button class="episode-row" data-episode="${i}" aria-pressed="${i===0}"><span>${e[0]}</span><span class="episode-track"><i style="width:${(e[1]-e[2])*4}%"></i><em style="width:${e[2]*4}%"></em></span><b>${e[1]}</b></button>`).join('')}</div><div class="depth-legend"><b><i></i>已确认方向</b><b><i class="unknown"></i>方向未定</b></div></div><aside class="depth-aside" data-episode-detail aria-live="polite"></aside></div>`,'来源：论文 §5 的 12 个 DPE 记录。横条是事件总数，不是表现分数；斜线是其中方向未定的事件。陈述与教练意见保留自己的来源范围，不能替代逐事件事实。');
  select(p,'data-episode',i=>{const e=episodes[i];$('[data-episode-detail]',p).innerHTML=`<span class="depth-code">${e[0]} / ${e[3]}</span><h4>${e[4]}</h4><dl><dt>事件 / 方向未定</dt><dd>${e[1]} / ${e[2]}</dd><dt>参与者陈述</dt><dd>${e[5]}</dd><dt>教练来源</dt><dd>${e[6]}</dd></dl>`;});add(1,p);
  add(2,flow('DPE / SEVEN EVIDENCE LAYERS','七层信息，各自保留来源。',[
   ['SOURCE','源视频与区间','双视角 · 片段边界','源视频是共同的检查入口。片段边界暂定时保留其状态，后续解释不覆盖原片。'],['EVENT','人工核验事件','方向与未知','事件序列区分 P01→P02 与 P02→P01；看不清或无法确定的方向保留 unknown。'],['GOAL','当场任务目标','目标卡 · 喂球计划','练习者想做什么、搭档打算如何提供条件分开保存，避免从动作反推意图。'],['ACCOUNT','双方分别陈述','时间范围 · 观看条件','参与者陈述保留说话者、当时或回访时的时间点，以及是否看过搭档的解释。'],['COACH','教练读片','独立来源 · 阶段范围','阶段级教练意见不伪装为精确片段判断；不在同一阶段的意见单独标明。'],['COMPUTED','计算候选','事件与区间','E / R / U 等输出帮助定位问题，但不自动定义练习成功、公平或关系质量。'],['UNKNOWN','未知登记','缺少锚点 · 方向未定','无法定位到某一拍的陈述可以停留在区间；未达成共识不被强行合并。']
  ],'依据论文 DPE 表征。图示层级是证据组织方式，不是七个连续自动化处理模块。','depth-architecture'),true);
 }

 if(id==='privacy-city'){
  add(2,flow('SYSTEM / EXPERIENCE ⇄ RESEARCH','从网页体验，到可复现的离线实验。',[
   ['BROWSER','授权情境','情境文本 → 用户选择','网页呈现模拟权限请求；记录阅读、选择与行为事件。界面反馈与研究评估分别组织。'],['RECORD','行为记录','事件 → 特征定义','把选择及阅读行为转成定义明确的字段。数据结构是模型与界面之间的接口，不将访客当前行为自动用于训练。'],['DATASET','实验数据','5,000 合成样本','当前比较基于合成数据：训练 3,500、验证 750、测试 750。这里不将合成数据结果写成真实用户预测能力。'],['MODEL','五条模型路线','MLP / Tree / Forest / LR','NumPy、PyTorch 的 MLP 与树模型、逻辑回归在同一实验口径下比较。训练在离线完成，不是浏览器即点即训。'],['EVALUATE','多角度检查','AUC / F1 / ECE / Brier','排序、分类、校准与概率误差各回答一个问题。上方交互比较保留固定 0—1 尺度和原始数值。'],['PRODUCT','回到界面','解释 → 原型调整','将情境、特征和评估分层，让设计判断能追溯。真实部署仍需独立的数据与同意流程。']
  ],'架构依据本地原型与实验材料；实线阅读顺序表示依赖关系，不表示已实现在线推理服务。','depth-architecture'),true);
  add(3,flow('NUMPY / COMPUTATION GRAPH','前向计算与反向更新，分开理解。',[
   ['01 / INPUT','48 维输入','X → W₁X + b₁','48 维行为特征进入第一层，48×64 + 64 = 3,136 个参数。批量大小改变张量的第一维，不改变模型参数数。'],['02 / HIDDEN','64 → 32','ReLU → ReLU','两个隐藏层采用 ReLU。第二层包含 64×32 + 32 = 2,080 个参数。'],['03 / OUTPUT','1 个概率','Sigmoid','输出层包含 32×1 + 1 = 33 个参数；三层合计 5,249。概率输出仍需要校准检查。'],['04 / UPDATE','误差回传','loss → gradient → update','训练阶段沿计算图反向传递梯度，再更新权重。此处是原理图，不执行训练或改变已报告的结果。']
  ],'模型宽度和参数来自项目原实现；原理图用实际维度表达，不用少量装饰节点冒充完整神经网络。'));
 }

 if(id==='baseball')buildBaseball();
 if(id==='afterglow')buildAfterglow();
 if(id==='growth-compass')buildGrowth();
 if(id==='looplab')buildLoop();
 if(id==='artemis')buildArtemis();
 if(id==='garden')add(4,flow('INTERACTION / CROSS PLATFORM','同一段探索，三层交互职责。',[
  ['NPC','对话与触发','发现 → 接近 → 对话','NPC 模块负责把场景中的人转成可以交互的叙事触点。玩家应看得见可操作状态，并能从对话返回探索。'],['CAMERA','视角与探索','观察 → 定位 → 行动','摄像机模块与角色输入协调，让对话和移动状态中的视角保持连贯；园景仍是玩家理解空间的主要依据。'],['ADAPTATION','小程序适配','网页输入 → 跨端交互','在团队 WebGL 游戏基础上改写与适配相关模块；区分团队整体游戏成果与个人负责的交互工作。']
 ],'对应个人负责的 NPC、摄像机与小程序适配；本图为职责架构，不将团队所有模块归为个人开发。','depth-architecture'));
 if(id==='bronze')add(3,flow('SHOT PRODUCTION / 镜头制作','从角色设定，到一个可交付镜头。',[
  ['DESIGN','人设与器灵','角色一致性','以原人设、器物形制和剧本动机约束视觉；角色参考独立于剧中截图标注。'],['STORYBOARD','分镜与视听','镜头组织','先明确人物关系、景别、动作与情绪，再进入图像与动画生成。'],['GENERATE','生成与返修','多轮素材选择','逐镜检查动作、脸部与服装一致性。生成素材是制作环节，不能替代导演选择与修复。'],['COMPOSITE','后期与成片','剪辑 / 声音 / 合成','在 After Effects、DaVinci 等后期流程中组织画面、声音与节奏，最终形成上方十集可观看成片。']
 ],'依据原项目人设、分镜与成片资料组织的制作流程。保留完整成片和集数时间码。'));

 // Implementations below are isolated to their project and do not replace TennisAtom.
 function buildBaseball(){
  const bench=$('.project-workbench');if(bench)bench.replaceWith(embed('Pitch / Impact · 原网站','demos/baseball/index.html','baseball-web-hero','原提交的 React 网站已本地接入：滚动叙事、图表实验室与 CSV 数据保留。部分球员图片来自原网站的 MLB 外链。'));
  const p=panel('STATCAST / SOURCE RECORDS','把每一球，放回空间。','↗',`<div class="depth-toolbar"><div role="group" aria-label="选择数据视角"><button data-ball-view="0" aria-pressed="true">山本 · 投球落点</button><button data-ball-view="1" aria-pressed="false">山本 · 位移分布</button><button data-ball-view="2" aria-pressed="false">大谷 · 击球速度 × 仰角</button></div><label>年份<select data-ball-year aria-label="数据年份"><option value="all">全部源记录</option><option>2024</option><option>2025</option><option>2026</option></select></label><label>球种<select data-ball-type aria-label="球种"><option value="all">全部球种</option></select></label></div><div class="depth-two"><div class="depth-big-plot" data-ball-plot></div><aside class="depth-aside" data-ball-aside aria-live="polite"></aside></div><details class="depth-pitch-copy"><summary>核对当前筛选的前 30 条有效记录</summary><div class="table-scroll" data-ball-table></div></details>`,'数据直接来自提交网站的山本与大谷逐球 CSV。每个点对应一条有效记录；缺失坐标不补零，筛选后的有效数与总数分别列出。2026 年数据仅覆盖文件已有日期，不代表完整赛季。');add(3,p,true);
  fetch('assets/baseball-records.json').then(r=>{if(!r.ok)throw Error('data unavailable');return r.json();}).then(data=>{
   let mode=0;const types=[...new Set(data.pitch.map(r=>r.pitch_type).filter(Boolean))].sort();$('[data-ball-type]',p).innerHTML='<option value="all">全部球种</option>'+types.map(x=>`<option>${esc(x)}</option>`).join('');
   const info=[['plate_x','plate_z','水平落点 / ft','垂直落点 / ft','投球位置','位置散点呈现球种与落点范围，不将一个统一方框冒充每位打者的实际好球带。'],['pfx_x','pfx_z','水平位移 / ft','垂直位移 / ft','球路位移','相同坐标系比较球种的位移分布；这不是三维轨迹重建。'],['launch_angle','launch_speed','击球仰角 / °','击球初速 / mph','击球结果','只显示同时有击球速度与仰角的接触记录，未发生击球不作为零值进入图中。']];
   function draw(){const f=info[mode],year=$('[data-ball-year]',p).value,type=$('[data-ball-type]',p).value;const subset=data[mode===2?'bat':'pitch'].filter(r=>(year==='all'||r.game_date.startsWith(year))&&(type==='all'||r.pitch_type===type)),rows=subset.filter(r=>Number.isFinite(r[f[0]])&&Number.isFinite(r[f[1]]));
    if(!rows.length){$('[data-ball-plot]',p).innerHTML='<p style="padding:40px">此筛选下没有有效坐标记录。</p>';$('[data-ball-aside]',p).innerHTML='<h4>无可绘制数据</h4><p>可以改选年份或球种。</p>';$('[data-ball-table]',p).innerHTML='';return;}
    const xs=rows.map(r=>r[f[0]]),ys=rows.map(r=>r[f[1]]);let x0=Math.floor(Math.min(...xs)),x1=Math.ceil(Math.max(...xs)),y0=Math.floor(Math.min(...ys)),y1=Math.ceil(Math.max(...ys));if(x0===x1)x1++;if(y0===y1)y1++;
    const X=v=>65+(v-x0)/(x1-x0)*525,Y=v=>414-(v-y0)/(y1-y0)*345;
    let grid='';for(let i=0;i<5;i++){const x=x0+(x1-x0)*i/4,y=y0+(y1-y0)*i/4;grid+=`<path class="grid" d="M${X(x)} 69V414 M65 ${Y(y)}H590"/><text x="${X(x)}" y="438" text-anchor="middle">${x.toFixed(mode===2?0:1)}</text><text x="54" y="${Y(y)+4}" text-anchor="end">${y.toFixed(mode===2?0:1)}</text>`;}
    $('[data-ball-plot]',p).innerHTML=`<svg class="depth-plot" viewBox="0 0 650 490" role="img" aria-label="${f[4]}散点图，${rows.length} 条有效记录"><title>${f[4]}</title><desc>${f[2]}与${f[3]}，当前 ${rows.length} 条有效记录。坐标范围按当前筛选显示。</desc>${grid}<path class="axes" d="M65 69V414H590"/>${rows.map(r=>`<circle class="mark" cx="${X(r[f[0]])}" cy="${Y(r[f[1]])}" r="2.6"><title>${esc(r.game_date+' / '+r.pitch_type+' / '+r[f[0]]+' / '+r[f[1]])}</title></circle>`).join('')}<text x="327" y="477" text-anchor="middle">${f[2]}</text><text x="65" y="37">${f[3]}</text></svg>`;
    const dates=subset.map(r=>r.game_date).sort();$('[data-ball-aside]',p).innerHTML=`<span class="depth-code">${mode===2?'SHOHEI OHTANI':'YOSHINOBU YAMAMOTO'}</span><h4>${f[4]}</h4><strong class="depth-big">${rows.length.toLocaleString()}</strong><p>有效点 / 筛选记录 ${subset.length.toLocaleString()}<br>坐标缺失 ${subset.length-rows.length} 条</p><p>${f[5]}</p><dl><dt>当前范围</dt><dd>${dates[0]} — ${dates.at(-1)}<br>${type==='all'?'全部球种':type}</dd><dt>坐标阅读</dt><dd>切换筛选时坐标轴随范围更新；比较球种时请保留“全部球种”视图作为背景。</dd></dl>`;
    $('[data-ball-table]',p).innerHTML=`<table class="model-table"><thead><tr><th>日期</th><th>球种</th><th>${f[2]}</th><th>${f[3]}</th></tr></thead><tbody>${rows.slice(0,30).map(r=>`<tr><th>${r.game_date}</th><td>${esc(r.pitch_type)}</td><td>${r[f[0]]}</td><td>${r[f[1]]}</td></tr>`).join('')}</tbody></table>`;
   }
   select(p,'data-ball-view',i=>{mode=i;draw();});$$('select',p).forEach(s=>s.addEventListener('change',draw));
  }).catch(()=>{$('[data-ball-plot]',p).innerHTML='<p style="padding:30px">原始数据暂时不可用，请打开上方原网站或演示视频。</p>';});
  add(1,panel('DESIGN / ORIGINAL PRESENTATION','从人物叙事，进入数据实验室。','04',`<div class="depth-inline">${image('baseball-original-08','原汇报：击球落点与球场空间')}${image('baseball-original-09','原汇报：球路位移与二维比较')}${image('baseball-original-07','原汇报：浏览、探索与局部放大')}</div>`,'以上来自原提交 PPT 的页面，点击可检查完整图。下方交互图直接读取原 CSV，二者保留各自版本口径。'));
  add(2,flow('FRONTEND / DATA PIPELINE','一套数据，连接三个阅读尺度。',[
   ['INGEST','四份 CSV','投手 / 打者 / 球队','Promise.all 并行加载球员与道奇队投打数据；使用 d3-dsv 解析，有限值与有效样本筛选在图表前完成。'],['MODEL','视图数据','聚合 / 筛选 / 编码','宏观层组织球队与球员指标，实验室按球种、位置和击球结果展开。详细逐球数据只在源文件覆盖的球员中提供。'],['RENDER','图表与空间','ECharts / Three.js','ECharts 承担雷达、散点、分布与比较；Three.js 与视觉模块组织空间和影像表达，不把效果层当作数据精度。'],['NARRATIVE','滚动与控制','React / GSAP / Lenis','React 管理菜单与视图，GSAP ScrollTrigger 与 Lenis 组织叙事节奏；浏览、选择、查看局部形成递进路径。']
  ],'架构依据原 src/App.tsx 与《项目结构与维护说明》。这是前端数据网站，无证据支持的后台服务不列为已实现。'));
  add(3,panel('ORIGINAL RECORDING','原提交 · 网页演示','▶',`<div class="depth-film"><video controls preload="none" poster="assets/baseball-web-macro.webp"><source src="media/baseball-original-demo.mp4" type="video/mp4"></video></div>`,'原提交文件夹中的演示视频；不自动播放。'));
 }
 function buildAfterglow(){
  $('.project-workbench')?.replaceWith(embed('AFTERGLOW · 原交互 V4','demos/afterglow/index.html','afterglow-web','接入原始 p5.js V4：同心字环、时间轴、四类输入与视觉手调。保留原程序 06:00—00:00 的 19 个内置演示时刻，不是当前站点实时监测。','https://heartfelt-haupia-dac532.netlify.app/'));
  add(2,flow('P5.JS / ENCODING ENGINE','把环境参数，写进同一组字环。',[
   ['INPUT','时序 / 手调','时间 → 四类输入','时序样本与手动输入是两种模式；原程序在相邻时刻之间平滑插值。插值画面是设计过渡，不是新增观测。'],['MAP','参数映射','密度 / 波形 / 字号 / 运动','人流同时改变方向数与环幅；噪声影响形变；PM2.5 调整字号与外圈；风改变相位和倾斜。字重由单独开关控制。'],['DRAW','逐字符绘制','角度 → 半径 → 字形','文本按径向层组织，字符依据角度逐个排布，再叠加波形和切变。V4 的单色中心圆随聚合量变化。'],['OUTPUT','多尺度输出','网页 / A3 / 空间','网页允许操作与导出；纸面检查字密度与比例；建筑效果图展示公共空间应用的设计提案。']
  ],'基于 AFTERGLOW_interactive(V4).html 的输入、映射与绘制结构。空间应用为设计方案。'));
  add(3,panel('ORIGINAL MOTION / WEB PROTOTYPE','字环运动，在原网页中发生。','▶',`<div class="depth-film"><video controls preload="none" poster="assets/afterglow-glyph.webp"><source src="media/afterglow-original-demo.webm" type="video/webm"></video></div>`,'原网页录屏作为加载或浏览器兼容性受限时的观看入口。实时操作请使用上方 V4 原型。'));
 }
 function buildGrowth(){
  const stages=[[
   ['探索兴趣','好奇，也不确定自己想学什么。','手机 H5 · 设计 DNA · 探索潜力图','进入选课平台，完成兴趣探索；输出好奇心引力场，不作能力诊断。','学生会 / 行政教师 / 校友职业资料','焦虑 → 好奇','秀米 / AI 概念'],
   ['预见课程','课程列表很多，需要理解能力指向。','课程星图 · WHY FIRST 预告 · 企业认证','查看 60 秒预告、课程案例和评价，将感兴趣课程加入试听清单。','教师录制预告 / 学生评价 / 企业参考','纠结 → 有期待','网站 / 课程内容'],
   ['低成本试听','先体验，再判断是否适合。','开放教室 · 微体验环节','在开放周参加小型任务；从真实案例与约五分钟练习中判断匹配度。','教务开放试听 / 教师设计微体验','兴奋 · 审视','教室 / 试听机制'],
   ['调整并承诺','做减法，确认自己的目标。','选课调整 · 智能换留推荐','查看冲突与时间支出，删去不合适课程，确认最终课表。','技术团队 / 学院教务','笃定 · 确认','选课逻辑 / Plan B'],
   ['成长留存','回看一学期学到了什么。','能力星图 · 成长节点','课程结束后点亮成长节点，回顾能力路径，为下轮选课提供依据。','平台维护 / 学习档案','充实 · 回顾','网站 / 成长记录']
  ],[
   ['理解任务','理解老师布置的模糊课题。','任务书 · 行业标准 · 课程平台','听取课题导入，浏览资源库，明确任务目标、约束与评价尺度。','课程教师 / 企业校友','困惑 · 找入口','任务书 / 平台'],
   ['强制支架','想开始设计，但不知道如何下手。','正反案例 · 设计逻辑 · 设计目标','先填写逻辑画布：目标、痛点、核心策略；对照案例自查，再启用 Agent。','技术团队 / 教务 / 案例库','受阻 → 有结构','逻辑画布'],
   ['即时预审','确认草稿基本要求，避免低级错误。','线上朋辈导师 Agent','上传基于画布完成的草稿；查看对齐、信息完整性等检查，快速修改基础问题。','朋辈导师 Agent 概念','确认 · 初步安心','预审规则 / 案例'],
   ['深入诊断','在教师意见后持续改进。','课程汇报 · Agent 深度交流','将老师建议带回迭代；结合行业参考与案例，讨论方案的深层逻辑。','老师 / 朋辈导师 Agent','挑战 · 深入交流','教师意见 / 诊断'],
   ['自信交付','提交作品，获得评价与认可。','结课成果 · 展示 · 作品档案','按照诊断修改并提交；参与期末讲评，记录课程技能与成果。','教师 / 校友共同反馈','完成 · 成就感','个人作品 / 档案']
  ]];
  let lane=0,active=0;const p=panel('SERVICE BLUEPRINT / 双旅程','选课与作业，共用一条成长线。','02',`<div class="depth-toolbar" role="group" aria-label="切换服务旅程"><button data-journey-lane="0" aria-pressed="true">课外 / 选择课程</button><button data-journey-lane="1" aria-pressed="false">课中 / 完成作业</button><span class="depth-code">点选阶段查看重点 · 小屏可横向滚动</span></div><div class="depth-blueprint-scroll" tabindex="0" aria-label="完整服务蓝图，横向滚动"><div class="depth-blueprint"></div></div><div class="depth-flow-detail" data-journey-focus aria-live="polite"></div>`,'依据原课外、课中旅程图重新排为可读的五阶段 × 多层蓝图。情绪是原方案的目标体验描述，不是已经测量的满意度结果。');
  function draw(){const a=stages[lane],img=lane?'growth-learning-journey':'growth-course-journey';let h='<div class="lane-name">阶段 / STAGE</div>'+a.map((s,i)=>`<button class="stage-head" data-stage="${i}" aria-pressed="${i===active}"><span>0${i+1}</span>${s[0]}</button>`).join('');
   const rows=[['原故事板',-1,'story-cell'],['目标与心态',1,''],['情绪 / 目标',5,'emotion-cell'],['触点与渠道',2,'touch-cell'],['用户行动',3,''],['后台与责任',4,'back-cell'],['工具与资源',6,'back-cell']];
   for(const [label,index,cl] of rows){h+=`<div class="lane-name">${label}</div>`+a.map((s,i)=>`<div class="${cl} ${i===active?'is-stage':''}" data-stage-cell="${i}">${index===-1?`<svg viewBox="${lane?375+i*302:330+i*291} ${lane?216:222} 190 103" role="img" aria-label="${s[0]}原故事板"><image href="assets/${img}.webp" width="2000" height="1125"/></svg>`:s[index]}</div>`).join('');}
   $('.depth-blueprint',p).innerHTML=h;$$('[data-stage]',p).forEach(b=>b.addEventListener('click',()=>{active=+b.dataset.stage;focus();}));focus();}
  function focus(){$$('[data-stage]',p).forEach((b,i)=>b.setAttribute('aria-pressed',String(i===active)));$$('[data-stage-cell]',p).forEach(c=>c.classList.toggle('is-stage',+c.dataset.stageCell===active));const s=stages[lane][active];$('[data-journey-focus]',p).innerHTML=`<strong>0${active+1}</strong><div><h4>${s[0]} / ${s[2]}</h4><p>${s[3]}</p></div>`;}
  select(p,'data-journey-lane',i=>{lane=i;active=0;draw();});add(4,p,true);
  const nodes=[['学生',450,445,'围绕个人目标完成画布、提交作业，再将反馈带回修改。'],['朋辈导师 Agent',260,230,'读取作业、调用案例与参考；输出建议，不替代教师评价。'],['教师',620,230,'明确课程目标、维护案例和行业尺度，并提供作业反馈。'],['学院',450,65,'提供课程能力地图与平台支持，协调课程与教学资源。'],['技术 / AI 模型',110,85,'为预审与案例组织提供技术支持。'],['企业 / 校友',795,85,'提供真实行业参考、实践经验与课程资源。'],['正反案例',125,375,'供学生自查，也作为预审模型和教学的参考。'],['行业标准',795,375,'连接教学尺度与行业经验，支持项目判断。'],['作业数据',450,310,'连接学生提交、Agent 读取与教师反馈，保留作品迭代。']];
  const edges=[[0,8],[8,1],[1,0],[2,0],[3,1],[3,2],[3,5],[4,1],[6,4],[6,0],[2,6],[2,1],[5,7],[7,2],[7,1]];
  const net=panel('SERVICE SYSTEM / 角色与资源','不是一个 Agent，而是一张支持网络。','09',`<div class="depth-network-index" role="group" aria-label="选择系统角色">${nodes.map((n,i)=>`<button data-sys-node="${i}" aria-pressed="${i===0}">${n[0]}</button>`).join('')}</div><div class="depth-system"><svg viewBox="0 0 900 505" role="img" aria-label="学生、教师、Agent、学院、技术与行业资源的服务关系"><title>Growth Compass 服务系统</title><desc>点击图中节点或上方角色可高亮相关连接。线表示资源、建议或支持，不表示数量。</desc><defs><marker id="growth-arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5 0 10" fill="#728c7f"/></marker></defs>${edges.map((e,i)=>`<path class="edge" data-sys-edge="${i}" d="M${nodes[e[0]][1]} ${nodes[e[0]][2]}L${nodes[e[1]][1]} ${nodes[e[1]][2]}" marker-end="url(#growth-arrow)"/>`).join('')}${nodes.map((n,i)=>`<g class="node" data-sys-mark="${i}"><circle cx="${n[1]}" cy="${n[2]}" r="48"/><text class="node-number" x="${n[1]}" y="${n[2]-7}" text-anchor="middle">${String(i+1).padStart(2,'0')}</text><text x="${n[1]}" y="${n[2]+18}" text-anchor="middle" style="font-size:12px">${n[0]}</text></g>`).join('')}</svg></div><div class="depth-flow-detail" aria-live="polite" data-sys-detail></div>`,'依据原系统图重绘：学生为核心，教学与朋辈支持、技术平台及行业资源分层协作。连接为服务概念关系，非已部署平台的运行监测。');
  $$('[data-sys-edge]',net).forEach((line,j)=>{const [a,b]=edges[j],s=nodes[a],t=nodes[b],dx=t[1]-s[1],dy=t[2]-s[2],len=Math.hypot(dx,dy);line.setAttribute('d',`M${s[1]+dx/len*50} ${s[2]+dy/len*50}L${t[1]-dx/len*50} ${t[2]-dy/len*50}`);});
  select(net,'data-sys-node',i=>{$$('[data-sys-mark]',net).forEach((n,j)=>{n.classList.toggle('active',i===j);n.setAttribute('aria-pressed',String(i===j));});$$('[data-sys-edge]',net).forEach((e,j)=>e.classList.toggle('active',edges[j].includes(i)));$('[data-sys-detail]',net).innerHTML=`<strong>0${i+1}</strong><div><h4>${nodes[i][0]}</h4><p>${nodes[i][3]}</p></div>`;});bindDiagram(net,'data-sys-mark','data-sys-node');add(5,net,true);
  add(2,flow('CONCEPT / TOUCHPOINTS','把模糊期待，转成下一步行动。',[
   ['EXPLORE','课程星图','兴趣 → 能力 → 课程','用兴趣探索和课程预告连接学习动机与具体课程，让选课发生在理解之后。'],['TRY','课程试听','预期 → 微体验 → 选择','开放周和微任务给学生低成本试错；试听后允许调整与确认，而非一次决定。'],['SCAFFOLD','设计逻辑画布','目标 → 痛点 → 策略','将任务理解外化为结构化画布。预审入口放在画布之后，让 AI 建议有明确的目标依据。'],['SUPPORT','朋辈支持与档案','预审 → 人工反馈 → 归档','基础问题先检查，复杂判断进入教师或朋辈交流，再把修改与成果保存为成长记录。']
  ],'概念图来自原方案的课程、试听、逻辑画布与朋辈支持触点，不将服务设想表述为已验证的学习效果。'));
 }
 function buildLoop(){
  const modules=[['材料交换','让剩余材料重新找到项目。','发布材料规格与余量 → 匹配需求 → 约定交接 → 确认收取',['纸板 / 板材','布料 / 皮革','其他余料']],['制作预约','先确认制作条件，再预约。','选择工艺 → 提交文件 → 确认时段 → 线下制作',['激光切割','3D 打印','工坊协作']],['小量团购','把零散需求组织成一笔采购。','提出需求 → 汇集数量 → 确认规格 → 统一取件',['材料规格','需求汇集','采购与交付']],['项目档案','保存作品，而不只是订单。','上传作品照片 / 3D 扫描 → 设计标签 → 项目回顾',['作品照片','3D 扫描','设计标签']],['校园取件','让线上约定有一个明确的终点。','查找触点 → 约定时间 → 到点交接 → 确认完成',['发布点','制作点','取件点']]];
  const p=panel('LOOPLAB / SERVICE MODULES','从一件余料，到下一次制作。','05',`<div class="depth-loop-board"><nav class="depth-loop-nav" aria-label="选择服务模块">${modules.map((m,i)=>`<button data-loop-module="${i}" aria-pressed="${i===0}">0${i+1} / ${m[0]}</button>`).join('')}</nav><div class="depth-loop-view" aria-live="polite"></div></div>`,'依据原 MVP 重构的可操作概念界面。示例材料与示意触点用于解释服务关系，不是实时库存或校园实际地图。');
  select(p,'data-loop-module',i=>{const m=modules[i];$('.depth-loop-view',p).innerHTML=`<span class="depth-code">SERVICE MODULE / 0${i+1}</span><h4>${m[1]}</h4><p>${m[3].join(' / ')}</p>${i===4?`<div class="depth-map"><svg viewBox="0 0 700 310" role="img" aria-label="校园触点关系示意，非真实地图"><title>发布、制作与取件的交接路线</title><path d="M30 80H670M30 225H670M160 20V290M470 20V290" stroke="#c8d0c1" stroke-width="35" fill="none"/><path class="route" d="M160 80H470V225H580"/>${[[160,80,'发布 / 匹配'],[470,80,'制作 / 预约'],[580,225,'交接 / 确认']].map((x,j)=>`<circle cx="${x[0]}" cy="${x[1]}" r="21" fill="#236656"/><text x="${x[0]}" y="${x[1]+6}" text-anchor="middle" style="fill:white">0${j+1}</text><text x="${x[0]}" y="${x[1]+48}" text-anchor="middle">${x[2]}</text>`).join('')}</svg></div>`:`<div class="depth-material-tickets">${m[3].map((x,j)=>`<article class="depth-ticket"><div class="material-sample">${['01','02','03'][j]}</div><h5>${x}</h5><small>${i===0?'规格、状态与交接方式一起描述':i===1?'文件要求与履约条件先确认':i===2?'数量与规格共同决定采购':i===3?'以作品为单位组织与复用':''}</small><b>${i===3?'PROJECT ARCHIVE':'SERVICE CONCEPT'}</b></article>`).join('')}</div>`}<div class="depth-step-ribbon">${m[2].split(' → ').map(s=>`<span>${s}</span>`).join('')}</div>`;});add(2,p,true);
  add(1,panel('BENCHMARK → DESIGN','借用机制，不复制整个平台。','05',`<div class="depth-comparison">${[['自提柜','自助交接','可明确的位置与取件流程','校园取件地图'],['闲鱼 / 校园群','闲置匹配','描述材料与连接供需','材料交换'],['Material Bank','材料信息','规范规格与样本组织','材料描述'],['电商制作','文件到履约','工艺、文件与时间约定','制作预约'],['云端档案','作品留存','照片 / 3D 扫描与标签','项目档案']].map((x,i)=>`<article><strong>0${i+1}</strong><h4>${x[0]}</h4><span class="depth-code">${x[1]}</span><div class="mechanism-line" aria-hidden="true"></div><p>${x[2]}</p><p>↓<br><b>${x[3]}</b></p></article>`).join('')}</div>`,'五类相邻产品提供不同的服务机制；条线是栏目分隔，不表达评分快慢或市场份额。'),true);
  add(3,flow('SERVICE / HANDOFF','每一步，都有线上信息和线下责任。',[
   ['MATCH','发现与匹配','材料信息 ⇄ 需求','线上描述规格、状态与需求，线下确认材料是否可用。匹配不是交付完成。'],['AGREE','约定与预约','数量 / 文件 / 时间','材料交换明确数量与交接；制作预约明确文件和工艺条件；团购先对齐规格。'],['FULFIL','制作与取件','制作点 ⇄ 取件点','预约、通知与校园地图连接具体位置；状态变化应对应真实交接动作。'],['RETAIN','归档与再使用','作品 → 标签 → 下一项目','项目档案保留作品照片或 3D 扫描，供后续回顾与复用，与材料库存分开组织。']
  ],'基于原线上线下服务旅程；此处展示服务概念的责任交接，不模拟真实订单或支付。'));
  const symbols=[
   ['<path d="M27 30L94 21 123 42 56 52ZM27 43L56 65 123 54M27 57L56 79 123 68"/>','<path d="M25 35Q44 5 64 35T103 35L125 67Q105 97 85 67T46 67Z"/><path d="M49 25L72 71M72 26L94 77"/>','<circle cx="75" cy="48" r="32"/><circle cx="75" cy="48" r="12"/><path d="M43 49V82H121M75 15V35M107 48H87M75 80V60M43 48H63"/>'],
   ['<path d="M25 75H125M35 75V21H111V75M72 21V39L66 48H81L75 39M74 49V66M67 66H81"/>','<path d="M41 37L75 19 110 37V73L75 91 41 73ZM41 37L75 55 110 37M75 55V91"/>','<path d="M28 74L51 53 75 75 105 43 126 65M29 29H120M43 18V40M73 18V40M104 18V40"/>'],
   ['<path d="M25 28H125V78H25ZM35 39H74M35 50H90M35 62H68"/>','<circle cx="38" cy="35" r="14"/><circle cx="112" cy="35" r="14"/><circle cx="75" cy="78" r="14"/><path d="M51 39L64 65M99 39L86 65M52 35H98"/>','<path d="M33 30L75 15 117 30V74L75 91 33 74ZM33 30L75 47 117 30M75 47V91M57 22L99 39"/>'],
   ['<path d="M23 18H127V88H23ZM30 78L56 47 78 68 99 44 122 78"/><circle cx="53" cy="34" r="6"/>','<path d="M43 36L75 18 109 36V74L75 91 43 74ZM43 36L75 53 109 36M75 53V91M22 26V12H37M113 12H129V26M22 78V92H37M113 92H129V78"/>','<path d="M29 20H79L122 62 80 100 29 53Z"/><circle cx="45" cy="37" r="5"/><path d="M71 42L99 68M60 54L84 77"/>']
  ];
  function paintSymbols(){const selected=+($('[data-loop-module][aria-pressed=true]',p)?.dataset.loopModule||0);$$('.material-sample',p).forEach((box,i)=>box.innerHTML=`<svg viewBox="0 0 150 110" aria-hidden="true">${symbols[selected]?.[i]||''}</svg>`);}
  new MutationObserver(paintSymbols).observe($('.depth-loop-view',p),{childList:true});paintSymbols();
 }
 function buildArtemis(){
  add(1,panel('GAME INTERFACE / ORIGINAL ART','完整界面，保留操作区域。','UI',`<div style="padding:20px;background:#101a30"><svg viewBox="1260 2450 1100 640" role="img" aria-label="原项目海报中的完整背包与构筑 UI"><title>背包与构筑界面</title><image href="assets/artemis-poster-3.webp" width="2444" height="3456"/></svg></div><div class="depth-inline">${image('artemis-original-01','原 UI 提案：主菜单初始状态')}${image('artemis-original-02','原 UI 提案：火箭发射与悬停状态')}${image('artemis-boss','原游戏 Boss 战实机')}</div>`,'背包画面取自原项目展示海报的 UI 区域；主菜单来自 uishow.pptx，作为设计提案标注。实机与提案不混称。'),true);
  add(2,flow('UNITY / GAMEPLAY ARCHITECTURE','输入、规则、状态与反馈分层协作。',[
   ['INPUT','动作意图','W / A / S / D','输入先变成相邻六边形目标，再检查格子存在、IsWalkable、高度差不超过 1 与指令冷却。'],['WORLD','空间与资源','Hex / Slot / Inventory','同一套 Hex 空间连接移动、槽位拾取与零件存取；世界规则提供动作执行条件。'],['STATE','角色状态','Idle → Start → Loop → End','状态切换管理进入、执行与退出；路径队列和动画 OnEnd 分工，持续移动时可更新目标而不重复起步。'],['BUILD','构筑效果链','Root → Neighbor → Effect','从根节点传递触发与效果，结合相邻零件和能量条件组织组合；构筑结构与战斗反馈相接。'],['ENEMY','敌人状态','预警 / 判定 / 阶段','Elite2 先标记射线格子，再进行命中检查；Elite1 按血量门槛转阶段，结合距离与冷却选择动作。'],['PRESENT','视听反馈','动画 / UI / 场景','动作、数值和状态变化反馈给玩家。设计关注前摇是否可读、状态退出是否清理，以及玩家能否理解结果。']
  ],'依据原 Unity 工程整理的客户端架构。个人负责角色与敌人行为、战斗及宣传表达；本图呈现已实现的客户端模块，不包含未经验证的服务端。','depth-architecture'));
  add(4,panel('ORIGINAL FILM / 04:33','从航天叙事，到游戏理念。','▶',`<div class="depth-embed-bar"><span>Aircraft, Artemis, Astronaut / 理念宣传片</span><a href="https://www.bilibili.com/video/BV1BurDBCEQP/" target="_blank" rel="noopener">打开 Bilibili 原视频 ↗</a><button data-artemis-play>在页面中播放</button></div><div data-artemis-film class="depth-film"><img src="assets/artemis-world.webp" alt="原项目世界观画面；点击播放理念宣传片" style="width:100%;height:100%;object-fit:contain"></div><div class="depth-inline">${image('artemis-arena','原游戏场景与战斗素材')}${image('artemis-poster-1','原展示海报：世界观、场景与游戏画面')}${image('artemis-poster-3','原展示海报：机制、零件与角色视觉')}</div>`,'原作品集链接已核对为 4 分 33 秒的理念宣传片；游戏实机截图以原项目素材另行呈现。站外播放受平台网络与登录策略影响。'));
  $('[data-artemis-play]')?.addEventListener('click',()=>{$('[data-artemis-film]').innerHTML='<iframe title="Artemis 原项目视频" src="https://player.bilibili.com/player.html?bvid=BV1BurDBCEQP&autoplay=0" allow="fullscreen" allowfullscreen style="width:100%;height:100%;border:0"></iframe>';$('[data-artemis-play]').remove();});
 }
})();
