/* Source-verified detail plates and flat animation art. No session cells are invented. */
(() => {
 'use strict';
 if(!document.body.classList.contains('rally-reference-edition'))return;
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const svg=(w,h,title,desc,b)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title><desc>${esc(desc)}</desc><metadata>RallyLens / original cobalt palette / source or schematic as described</metadata>${b}</svg>`;
 const crop=(key,box,w,h,title)=>svg(...box.split(' ').slice(2).map(Number),title,'原论文图局部，不改动图内数据。',`<svg viewBox="${box}" width="100%" height="100%"><image href="assets/refinement/${key}.webp" width="${w}" height="${h}"/></svg>`);
 const pair='assets/rally-flat-pair-v1.webp';
 $$('.rally-sheet img[src="assets/rally-ink-pair-v1.webp"]').forEach(i=>i.src=pair);
 const review=$('.rally-review-art');if(review)review.src='assets/rally-flat-review-v1.webp';
 document.body.insertAdjacentHTML('beforeend',`<svg class="rally-glyph-defs" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs><symbol id="rally-shuttle" viewBox="0 0 100 100"><g fill="none" stroke="currentColor" stroke-width="2"><path d="M40 72L8 13Q50 3 92 13L60 72Z"/><path d="M20 11l24 61M35 8l12 64M50 8v64M65 8L53 72M80 11L56 72M21 37q30-8 58 0M31 56q20-5 39 0"/><path d="M40 72h20v10q-10 15-20 0Z" fill="currentColor"/></g></symbol><symbol id="rally-racket" viewBox="0 0 100 130"><g fill="none" stroke="currentColor" stroke-width="2"><ellipse cx="50" cy="36" rx="28" ry="32"/><ellipse cx="50" cy="36" rx="24" ry="28"/><path d="M34 14v44M42 10v52M50 8v56M58 10v52M66 14v44M28 20h44M26 28h48M26 36h48M26 44h48M28 52h44M41 67l9 12 9-12M50 79v27"/><rect x="46" y="106" width="8" height="22" fill="currentColor"/></g></symbol><symbol id="rally-court" viewBox="0 0 300 145"><g fill="none" stroke="currentColor" stroke-width="1.4"><rect x="15" y="15" width="270" height="115"/><path d="M15 25h270M15 120h270M150 15v115M85 15v115M215 15v115M15 72.5h70M215 72.5h70M27 15v115M273 15v115"/><path d="M150 4v137" stroke-width="3"/></g></symbol></defs></svg>`);
 const use=(name,cls='')=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${name==='racket'?'0 0 100 130':name==='court'?'0 0 300 145':'0 0 100 100'}" class="${cls}" aria-hidden="true"><use href="#rally-${name}"/></svg>`;
 $('.rally-cover-mark svg')?.replaceWith(new DOMParser().parseFromString(use('shuttle'),'image/svg+xml').documentElement);
 $('.rally-cover-mark span').innerHTML='PERSON ↔ PERSON<br>每次来球，都是下一次机会';
 $('.rally-cover .rally-source-fold')?.setAttribute('open','');
 // Six problems → six fields: conceptual design relations, not measured network weights.
 const themes=['互相形成练习条件','不同的共同活动理解','解释如何指向证据','跨片段、跨时段回顾','每个人的成功标准','镜头无法确认的部分'];
 const fields=['方向','陈述','锚点','范围','标准','未知'];
 let map='';themes.forEach((t,i)=>{const y=40+i*44;map+=`<text x="6" y="${y+4}">${t}</text><circle cx="168" cy="${y}" r="3"/><path d="M168 ${y}L235 ${y}"/><circle cx="235" cy="${y}" r="3"/><text x="247" y="${y+4}">${fields[i]}</text>`;});
 map+='<path d="M168 40L235 260M168 84L235 128M168 172L235 128" stroke-dasharray="3 4"/>';
 $('.rally-contract').insertAdjacentHTML('beforebegin',`<figure class="rally-field-map">${svg(315,295,'研究问题如何进入记录字段','连线表示设计关联，没有权重。依据论文问题与表征要求重排。',`<g fill="#111719" font-family="Arial, Microsoft YaHei, sans-serif" font-size="12">${map}</g>`)}<figcaption>问题 → 字段 / 设计关系，不是统计相关性</figcaption></figure>`);
 const protocol=$('.rally-blue-panel .rally-protocol');
 const stages=[['自由对打','双方通常的打法','自由','自由'],['角色阶段 A','一人练习，一人提供条件','练习','喂球'],['角色互换','交换实践与支持的位置','喂球','练习'],['计分回合','目标进入比赛条件','计分','计分']];
 if(protocol){
  $('.rally-protocol-art').innerHTML='<img src="assets/rally-flat-hall-v1.webp" alt="AI生成的双机位球馆布置场景示意，非研究实景或定位结果"><small>场地与双机位 / AI 场景示意，非实景</small>';
  protocol.innerHTML=stages.map(([t,d,a,b],i)=>`<li><div class="rally-stage-court">${svg(300,160,t+'场地流程示意','人物和球路仅说明阶段与角色，不表示实测位置或轨迹。',`<g color="#f5f6f2"><use href="#rally-court" x="0" y="24" width="300" height="120"/></g><circle cx="70" cy="83" r="8" fill="#fff"/><rect x="225" y="76" width="14" height="14" fill="#fff"/><path d="${i===1?'M215 80Q140 45 87 80':i===2?'M88 87Q145 110 215 87':'M87 80Q150 45 215 80M215 88Q150 120 87 88'}" stroke="#fff" fill="none" stroke-dasharray="3 4"/><g fill="#fff" font-family="Arial, Microsoft YaHei, sans-serif" font-size="13"><text x="70" y="18" text-anchor="middle">○ ${a}</text><text x="231" y="18" text-anchor="middle">□ ${b}</text></g>`)}<div class="rally-stage-objects">${use('racket')}${use('shuttle')}</div></div><b>0${i+1}</b><div><h3>${t}</h3><p>${d}</p></div></li>`).join('');
 }
 // Coding chain: a schematic, not a inferred ball trajectory.
 const coding=svg(340,240,'逐事件编码的检查链','球路是示意线，不是跟踪坐标。画面确认击球方向、过网与接触，未知保留为未知。',`<image href="${pair}" x="5" y="40" width="325" height="108"/><path d="M77 103Q168 5 266 103" fill="none" stroke="#2354d8" stroke-width="1.5" stroke-dasharray="3 4"/><path d="M168 62v85M20 148h300" stroke="#2354d8" fill="none"/><g fill="#2354d8"><circle cx="85" cy="98" r="3"/><circle cx="259" cy="91" r="3"/></g><g font-family="Arial, Microsoft YaHei, sans-serif" font-size="11" fill="#111719"><text x="22" y="174">谁 → 谁</text><text x="118" y="174">越过球网</text><text x="231" y="174">回应接触</text><text x="22" y="195">方向或未知</text><text x="118" y="195">进入条件</text><text x="231" y="195">下一次机会</text><text x="22" y="228">没有回应 ≠ 回应未确认</text></g><path d="M89 179h17M198 179h18" stroke="#111719"/>`);
 $('.rally-code-callout').insertAdjacentHTML('beforebegin',`<figure class="rally-coding-chain">${coding}<figcaption>球拍、羽毛球与越网动作的编码示意</figcaption></figure>`);
 // AUC ranges from §5.3: reported ranges across indicators, not confidence intervals.
 let auc='<path d="M50 145H300M175 24V145" stroke="#8e9bad" fill="none" stroke-dasharray="3 4"/><g font-family="Arial, Microsoft YaHei, sans-serif" fill="#111719" font-size="12"><text x="6" y="18">有效进入 / 可达 / 可用回应</text><text x="6" y="82">连续性</text><text x="50" y="167" text-anchor="middle">0</text><text x="175" y="167" text-anchor="middle">.50</text><text x="300" y="167" text-anchor="middle">1.00</text><text x="185" y="128">随机区分参考</text></g>';
 [[.45,.50,43],[.55,.62,105]].forEach(([a,b,y])=>{auc+=`<path d="M${50+a*250} ${y}H${50+b*250}" stroke="#2354d8" stroke-width="6"/><path d="M${50+a*250} ${y-7}v14M${50+b*250} ${y-7}v14" stroke="#2354d8"/><text x="${50+b*250+9}" y="${y+4}" fill="#111719" font-family="Arial" font-size="12">${a.toFixed(2)}–${b.toFixed(2)}</text>`;});
 $('.rally-auc-note').insertAdjacentHTML('beforeend',`<figure class="rally-auc-chart">${svg(340,180,'目标域模型的原报告AUC范围','范围是论文§5.3报告的不同指标值域，不是置信区间。共享0至1轴，.5为随机区分参考。',auc)}<figcaption>原报告范围 / 不是置信区间</figcaption></figure>`);
 $('.rally-auc-note').insertAdjacentHTML('afterend',`<div class="rally-source-thumbs">${[['figS2_goal_parent_dimensions','01 / 八维分解'],['fig04_goal_heatmap_g01_02','02 / 方向热图'],['../composition/figS6_rallylens_layer1','03 / 回放层'],['fig05_rallylens_three_layers','04 / 估计层']].map(([k,t])=>`<a href="assets/refinement/${k}.webp" target="_blank" rel="noopener"><img src="assets/refinement/${k}.webp" alt="${t}原论文图" loading="lazy"><span>${t} ↗</span></a>`).join('')}</div>`);
 // Original fixed A-view replaces the generic training photo in the finding case.
 const shared=$('.rally-finding-columns>article:nth-child(2) .rally-source-figure');
 if(shared)shared.innerHTML=`<a href="assets/refinement/fig01_shared_rally.webp" target="_blank" rel="noopener" aria-label="打开G01_02共享案例原图">${crop('fig01_shared_rally','30 202 780 440',2000,1588,'G01_02固定事件2的原A视角')}</a><figcaption>原 Fig.1 / #02 · 6.80 s · 不是逐帧同步画面</figcaption>`;
 // Entire Table 2, counted dots. Dot index is not an observed session identifier.
 const counts=[['喂球计划相同',1,16,'角色阶段'],['喂球计划相反',6,16,'角色阶段'],['相反计划但双方满意',3,6,'相反计划阶段'],['选择相同目标',6,16,'角色阶段'],['双方自评理解一致',6,15,'可比较双人评分'],['个人自评理解一致',21,31,'个人评分'],['双方认为伙伴匹配',4,14,'可比较双人评分'],['双方认为难度相同',10,14,'可比较双人评分']];
 $('[data-rally-card-comparison]').innerHTML=`<div class="rally-card-matrix"><div class="rally-matrix-key"><span>● 计入该项</span><span>○ 其余</span></div>${counts.map(([t,n,d,u])=>`<div class="rally-matrix-row"><div><span>${t}</span><b>${n}<i> / ${d}</i></b></div><div class="rally-count-dots" role="img" aria-label="${esc(t)}：${n}，分母${d}，${u}">${Array.from({length:d},(_,i)=>`<i class="${i<n?'filled':''}" aria-hidden="true"></i>`).join('')}</div><small>分母：${d} ${u}</small></div>`).join('')}<p>圆点仅表示汇总数量，不对应具体场次或球员；分母保留原表的可比较范围。</p></div>`;
  $('[data-rally-card-comparison]').nextElementSibling.textContent='原论文 Table 2 / 可比较的阶段卡子集。各项统计单位与分母不同，不能直接相减，也不代表新增回访人数。';
  // Three source case drawings remain visible, not buried entirely in the atlas.
 const cases=[['G07_03 / 练习条件','20 335 610 325','球不挑高，练习才持续。','P09 描述有意送前场球；P10 把双方都保持低球作为练习成立的条件。'],['G03 / 片段定位','25 822 610 265','共同练习，定位在不同片段。','P06 选择 G03_02 的送球安排；P05 选择聊天后更放松的 G03_03。'],['G01_04 · G03_02 / 重复','10 1485 650 450','重复可以跨越独立尝试。','一位记得类似来球的再次成功，另一位记得放松后原目标变得容易遗忘。']];
 $('[data-rally-finding-slot]').insertAdjacentHTML('beforebegin',`<div class="rally-findings-detail">${cases.map(([code,box,t,d])=>`<article><span class="rally-small">${code}</span>${crop('fig02_findings_contrasts',box,2000,1993,t+'原研究示意图')}<h3>${t}</h3><p>${d}</p></article>`).join('')}</div><p class="rally-inline-note">原论文 Fig.2 / 三个案例各自保留时间范围，中文为原陈述意译。</p>`);
 // Native source-region leaders, referenced to the inspected Fig.5 image.
 const annotations=[['01','同一事件的选择','6.80 s 的位置贯穿三层',510,60,67],['02','两个相反机位','原 B-view 与主画面并列',345,218,170],['03','候选而非成效','Offer / Actual-model 另有来源',515,235,274],['04','每个回合的边界','轨迹断点与未知不被补齐',270,424,382],['05','独立的双方解释','分别保留来源与时间范围',280,551,508],['06','第三方读法','教练来自同阶段另一窗口',330,637,622]];
 let leaders=`<rect width="1040" height="720" fill="#f5f6f2"/><image href="assets/refinement/fig05_rallylens_three_layers.webp" x="5" y="5" width="610" height="663"/>`;
 annotations.forEach(([n,t,d,x,y,ly])=>{leaders+=`<g font-family="Arial, Microsoft YaHei, sans-serif"><path d="M${x} ${y}H635V${ly}H661" stroke="#2354d8" fill="none" stroke-width="1.2"/><circle cx="${x}" cy="${y}" r="10" fill="#2354d8"/><text x="${x}" y="${y+4}" text-anchor="middle" font-size="10" fill="#fff">${n}</text><text x="675" y="${ly+3}" font-size="20" fill="#111719" font-weight="700">${n} / ${t}</text><text x="675" y="${ly+30}" font-size="15" fill="#34435a">${d}</text></g>`;});
 $('[data-rally-account-slot]').insertAdjacentHTML('beforebegin',`<section class="rally-annotated-interface"><span class="rally-small">SOURCE FIG.5 / INTERFACE ANATOMY</span><h3>界面的每一层，回应一个研究问题。</h3>${svg(1040,720,'原Fig.5的六处界面与证据注释','引线对应原截图中的事件、B视角、估计、序列、双方解释与教练陈述。不把静态原图伪装为在线同步视频。',leaders)}<div class="rally-annotation-mobile">${annotations.map(([n,t,d])=>`<p><b>${n} / ${t}</b><span>${d}</span></p>`).join('')}</div><p class="rally-inline-note">原型截图保留原图配色；蓝色编号与引线为本次编辑注释。点图可核对原 Fig.5。</p><a href="assets/refinement/fig05_rallylens_three_layers.webp" target="_blank" rel="noopener" class="rally-source-link">查看完整原型图 ↗</a></section>`);
 // Replace decorative generic source rows with compact, specific badminton objects.
 $('.rally-symbol-legend').insertAdjacentHTML('afterend',`<div class="rally-object-key">${use('racket')}${use('shuttle')}${use('court')}<span>来球 → 回应 → 下一次机会<br><small>场地与对象示意 / 非定位数据</small></span></div>`);
 document.body.classList.add('rally-detail-edition');
 $('.rally-annotated-interface').tabIndex=0;
 $('.rally-annotated-interface').setAttribute('aria-label','原型六处注释；手机可横向滚动，文字说明另列在图下');
 // Immediate navigation supports reading; the inherited global smooth-scroll handler is bypassed only here.
 document.addEventListener('click',ev=>{const a=ev.target.closest('a[href^="#"]');if(!a)return;const target=document.getElementById(a.getAttribute('href').slice(1));if(!target)return;ev.preventDefault();ev.stopImmediatePropagation();history.replaceState(null,'',a.getAttribute('href'));target.scrollIntoView({behavior:'instant',block:'start'});},true);
})();
