/* Portfolio interaction layer. Existing project assets remain distinct from new UI demonstrations. */
(() => {
  'use strict';
  const P=window.PORTFOLIO, $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sizes={'rally-ui':[1683,909],'privacy-compare':[1274,717],'tennis-real-5':[1920,1080],'artemis-world':[1280,675],'bronze-character':[1500,1500],'baseball-web-hero':[1920,1080],'afterglow-glyph':[689,345],'growth-tasting-original':[2000,1091],'loop-materials':[816,977],'garden-title':[1600,903],'garden-autumn':[1600,903],'garden-winter':[1600,903],'garden-spring':[1600,903],'garden-summer':[1600,903],'garden-fan':[1600,903],'garden-tour':[1600,903]};
  const img=(n,a,cls='',eager=false)=>`<img class="${cls}" src="assets/${n}.webp" alt="${esc(a)}" ${sizes[n]?`width="${sizes[n][0]}" height="${sizes[n][1]}"`:''} loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''} decoding="async">`;
  const routes={product:['rallylens','tennisatom','privacy-city','growth-compass','looplab'],game:['artemis','garden'],ai:['bronze','privacy-city','growth-compass','tennisatom'],data:['baseball','afterglow','rallylens','tennisatom']};
  const C={
    rallylens:{tag:'PRODUCT / RESEARCH',cover:'rally-ui',detail:'rally-accounts',lead:'同一段练习，保留两个人的理解。',action:'查证据 → 看双方解释 → 讨论下一步',assets:[['rally-ui','原型回放与事件定位'],['rally-timeline','时间线与方向性事件'],['rally-accounts','双方陈述并列'],['rally-braid','交换顺序的可视化']],decisions:[['回放先行','球员难以把说明定位到单次击球。界面把视频和时间范围放在首层，允许解释指向一个区间。','回放 / 区间定位'],['并列保留','一方的解释没有消除另一方的经验。双方陈述保留作者、来源和范围，分别阅读。','双人陈述 / 来源标签'],['候选可检查','计算结果单独展开，旁边保留定义、输入范围和未知。用户能回到事件核对。','证据抽屉 / E · R · U'],['计划有状态','回看后的建议可能仍有分歧。拟议、讨论、双方确认和未解决分别呈现。','计划版本 / 独立确认']]},
    'privacy-city':{tag:'AI TOOL / EVALUATION',cover:'privacy-compare',detail:'privacy-scene1',lead:'把隐私选择，接到可解释的评测工具。',action:'体验授权情境 → 整理行为特征 → 比较离线模型',assets:[['privacy-start','原游戏起始界面'],['privacy-scene1','玩家授权情境'],['privacy-compare','原模型评测工作台']],decisions:[['情境承载选择','请求、奖励和选择放在同一个场景中，玩家能理解授权发生的上下文。','请求用途 / 接受与拒绝'],['体验与评测分层','网页提供规则反馈，离线实验处理行为特征和模型评估，数据来源保持明确。','游戏端 / 实验端'],['多指标比较','AUC、F1、ECE 和 Brier 分别回答排序、分类和概率质量问题。比较表保留全部指标。','共同尺度 / 指标说明'],['工具可复用','特征准备、基线比较、消融和校准分析形成工作流程，便于替换情境与模型。','配置 / 训练 / 检查']]},
    tennisatom:{tag:'PRODUCT / CREATIVE TOOL',cover:'tennis-real-5',detail:'tennis-poster',lead:'为每一位球员，做一支属于自己的影片。',action:'明确观看动机 → 选择动作与视觉 → 审看个人成片',assets:[['tennis-poster','身体的肖像 · 主视觉海报'],['tennis-trace','动作轨迹设计物料'],['tennis-pose','姿态结构设计物料'],['tennis-impact','冲击特效设计物料'],['tennis-real-3','真人竖屏与动态文字']],decisions:[['从表达动机开始','记录成长、感受动作、理解战术和表达情绪需要不同观看方式。制作入口先明确目的。','四类观看动机'],['信息与视觉配合','轨迹解释路径，骨骼说明姿态，特效回应动作节奏，分别承担不同阅读任务。','轨迹 / 姿态 / 冲击'],['真人素材为主体','片段选择与叙事围绕具体参与者展开，生成与特效接入其真实运动影像。','五支真人定制成片'],['个人选择保留','情绪、关键词、颜色和节奏由参与者参与选择。动作轨迹不能自动证明人格。','人工审看 / 媒体适配']]},
    artemis:{tag:'GAME / SYSTEM DESIGN',cover:'artemis-world',detail:'artemis-build',lead:'从相邻一格，到可以组合的战斗系统。',action:'探索 → 构筑 → 预警与判定 → 调整行动',assets:[['artemis-world','重返星海世界观视觉'],['artemis-build','零件构筑与游戏界面'],['artemis-boss','Boss 战实机素材'],['artemis-arena','战斗场景与机制']],decisions:[['移动先校验','WASD 给出相邻六边形目标；边界、可行走性、高度差和冷却满足后才提交路径。','输入 → 路径检查'],['动画接续状态','起步和停步由动画结束事件接续，持续移动检查队列和目标距离。','待机 / 起步 / 移动 / 停步'],['构筑分步执行','左键启动根节点，右键推进后续层级；能量与修饰数据沿连接关系传递。','槽位 / 能量 / 子节点'],['敌人给出行动线索','钩爪预警与判定使用相同格子范围，阶段变化连接到血量门槛和退出清理。','预警 / 避让 / 恢复']]},
    bronze:{tag:'ANIMATION / ORIGINAL FILMS',cover:'bronze-ep06-4',detail:'bronze-xingchen-study',lead:'从十集成片进入故事。',action:'选择剧集 → 观看原片 → 从时间码回查画面',assets:[],decisions:[]},
    baseball:{tag:'DATA PRODUCT / WEB',cover:'baseball-web-hero',detail:'baseball-web-detail',lead:'先进入球员故事，再走进数据实验室。',action:'人物叙事 → 指标概览 → 空间分布与细节',assets:[['baseball-web-hero','原网站球员叙事首页'],['baseball-web-lab','图表实验室'],['baseball-web-macro','投打分析概览'],['baseball-web-detail','指标与空间细节'],['baseball-web-atlas','多视角数据章节']],decisions:[['建立浏览节奏','人物大画面提供入口，随后按球员、时间和投打信息展开，避免同时堆出全部图表。','概览 → 实验室'],['视角各有口径','投球位置、速度和击球结果需要不同尺度；标题和说明交代当前比较任务。','分组 / 统计范围'],['图形与数字相邻','空间图形帮助读位置，精确数值帮助核对表现；两者保持同一阅读上下文。','点分布 / 数值卡'],['代码支持设计','CSV 整理、React 页面和 ECharts、GSAP、Three.js 交互共同完成可演示原型。','数据 → 图表 → 网页']]},
    afterglow:{tag:'GENERATIVE DESIGN / DATA',cover:'afterglow-glyph',detail:'afterglow-dome',lead:'四种环境信号，聚成一个可以阅读的环。',action:'读取数据 → 径向编码 → 时间切换 → 空间提案',assets:[['afterglow-glyph','最终核心径向视觉'],['afterglow-map','原项目四类视觉编码'],['afterglow-web','可访问 p5.js 原型'],['afterglow-dome','公共空间提案效果图']],decisions:[['一类信号一个通道','人流、噪声、PM2.5 与风分配到不同视觉属性，变化能回溯到对应输入；V4 的字重为独立手动控制。','径向密度 / 振幅 / 字号与外圈 / 倾斜'],['统一图形骨架','不同时间保持径向识别，调整尺度、文字和信号强度，使样本可以比较。','稳定骨架 / 状态比较'],['数据异常可处理','CSV 读取、插值与异常展示贯穿 V3、V4 实现，避免失效数据打断浏览。','读取 / 插值 / 备用显示'],['屏幕延伸到空间','建筑效果图检查观看位置与尺度；目前交付为网页原型与设计提案。','数字原型 / 场景效果']]},
    'growth-compass':{tag:'SERVICE PRODUCT / AGENT CONCEPT',cover:'growth-tasting-original',detail:'growth-clinic-original',lead:'先理解课程，再决定自己怎么学。',action:'课程预览 → 作业支架 → 朋辈问诊 → 成长档案',assets:[['growth-tasting-original','模块化试听 · 原项目故事板'],['growth-canvas-original','作业逻辑画布 · 原项目概念'],['growth-stuck-original','学习卡住与支持触点'],['growth-clinic-original','朋辈问诊概念'],['growth-system','课前服务系统'],['growth-personas','团队研究综合画像']],decisions:[['意义前置','原研究发现课程期待在选课时已经形成。预览先显示能力指向、内容与适配人群。','课程导航 / 模块化试听'],['补上过程支架','布置作业与最终评分之间需要思考工具。逻辑画布帮助表达目标、依据和执行步骤。','作业画布 / 正反案例'],['朋辈 Agent 概念','原方案提出作业预审与朋辈导师 Agent，提供对齐、逻辑和案例反馈，再转交人。','预审概念 / 人工问诊'],['后台支撑前台','教师提供目标与案例，教务安排调整窗口，朋辈与校友提供资源和反馈。','服务蓝图 / 协作角色']]},
    looplab:{tag:'SERVICE PRODUCT / MVP',cover:'loop-materials',detail:'loop-demo-poster',lead:'让一次材料需求，有完整的交接路径。',action:'查询与发布 → 规格确认 → 制作或交换 → 线下取件',assets:[['loop-materials','校园材料流转视觉'],['loop-demo-poster','原服务概念视频画面']],decisions:[['从履约比较开始','比较闲鱼、Material Bank 和电商制作服务，分别检查材料信息、交易与制作交付。','三类竞品模式'],['范围先收敛','交换、团购、制作预约、档案和取件组成 MVP 范围，承接学生一次具体需求。','五类服务模块'],['信息足以交接','类型、规格、状态、数量与时间是确认材料需求的必要信息，线上操作连到线下核对。','材料详情 / 交接状态'],['统一方案表达','内容与视觉重构串联需求、流程和商业模式，使服务触点与履约路径在同一套方案中对应。','需求 → 方案 → 履约']]},
    garden:{tag:'GAME / CULTURAL PUZZLE',cover:'garden-title',detail:'garden-autumn-overview',lead:'改一个字，改变一处园景。',action:'入梦 → 与园主相遇 → 奇扇改字 → 四季游园',assets:[['garden-title','原游戏标题画面'],['garden-fan','奇扇改字界面'],['garden-season-select','游览模式四季选择'],['garden-tour','照片与园林知识'],['garden-exhibit','团队项目展台物料']],decisions:[['四季承接叙事','秋、冬、春、夏承接人物相遇与园林变迁，同一空间在不同章节中继续展开。','团队游戏 / 四季章节'],['字义接到反馈','奇扇把诗句中的文字变为操作对象，改字后通过雾散、月现等园景变化回应选择。','团队游戏 / 改字解谜'],['两种体验入口','剧情模式承担解谜与人物叙事；游览模式以漫步、照片和文字承接园林知识阅读。','剧情 / 自由游览'],['个人跨端工作','NPC 与摄像机模块是个人改写范围，微信小程序适配延续探索和对话关系。','个人分工 / 2025.12—2026.01']]}
  };
  const buttons=(items,key,active=0)=>`<div class="studio-tabs" role="group" aria-label="${({rally:'证据阅读层级',metric:'模型评估指标',motive:'观看动机',character:'角色参考',service:'服务阶段',atlas:'界面阅读尺度',garden:'四季、奇扇与游览实机画面'})[key]||'切换展示'}">${items.map((s,i)=>`<button data-studio-${key}="${i}" aria-pressed="${i===active}">${esc(s)}</button>`).join('')}</div>`;
  const select=(root,key,i)=>$$(`[data-studio-${key}]`,root).forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset['studio'+key[0].toUpperCase()+key.slice(1)]===i)));
  const imageButton=(n,a)=>`<button class="studio-image" data-art="${n}" data-art-caption="${esc(a)}" aria-label="放大：${esc(a)}">${img(n,a)}</button>`;
  C.afterglow.assets.push(['afterglow-source-poster','原项目 A3 视觉输出']);
  C['growth-compass'].assets.push(['growth-course-journey','课外服务旅程 · 目标体验'],['growth-learning-journey','课中服务旅程 · 目标体验']);
  function home(){
    document.body.classList.add('studio-home');
    $('.hero-cta').insertAdjacentHTML('afterend','<div class="hero-directions"><a href="#work" data-route-short="product">产品与服务 ↗</a><a href="#work" data-route-short="game">游戏交互 ↗</a><a href="#work" data-route-short="ai">AI 工作流 ↗</a></div>');
    $('.work-heading').innerHTML='<div><p class="hand">selected work /</p><h2 id="work-title">把想法做成<br><em>可操作的作品。</em></h2></div><div class="work-editor-note"><span>PRODUCT · GAME · AI</span><p>从研究到界面，从视觉到实现。<br>选择一条路线，进入项目的设计与操作。</p></div>';
    $('.filter-row').outerHTML='<div class="studio-discovery"><div class="route-tabs" role="group" aria-label="作品浏览路线"><button data-route="all" aria-pressed="true">全部作品 <sup>10</sup></button><button data-route="product" aria-pressed="false">产品与服务</button><button data-route="game" aria-pressed="false">游戏交互</button><button data-route="ai" aria-pressed="false">AI 工作流</button><button data-route="data" aria-pressed="false">数据体验</button></div><div class="work-search"><label for="work-query">搜索项目</label><input id="work-query" type="search" placeholder="项目、设计或技术关键词"><button id="work-clear" aria-label="清空项目搜索">×</button></div></div><p class="route-description" aria-live="polite">10 个项目 · 打开案例可操作原型、查看设计决策与原始资产。</p>';
    const catalog=$('#project-grid');catalog.className='studio-catalog';
    catalog.innerHTML=P.projects.map(p=>{const c=C[p.id];return `<article class="portfolio-entry entry-${p.id}" data-project="${p.id}" style="--entry-accent:${p.color};--entry-tone:${p.tone}"><div class="entry-top"><span>${p.number} / ${c.tag}</span><span>${p.year}</span></div><a class="entry-art" href="case.html?project=${p.id}" aria-label="打开 ${esc(p.name)} 案例">${c.cover?img(c.cover,p.name+' 原项目视觉与界面'): '<div class="garden-letter"><span>园</span><small>EXPLORATION<br>CULTURE / DIALOGUE</small></div>'}${c.detail?`<div class="entry-inset">${img(c.detail,p.name+' 原项目设计细节')}</div>`:''}<span class="entry-open">打开案例 ↗</span></a><div class="entry-copy"><div><p>${p.label}</p><a href="case.html?project=${p.id}"><h3>${p.name}</h3></a><h4>${p.cn}</h4></div><div><p class="entry-claim">${c.lead}</p><p class="entry-task">${c.action}</p><p class="entry-role">${p.role}</p><a class="entry-link" href="case.html?project=${p.id}#experience">体验项目 <span>↗</span></a></div></div></article>`;}).join('');
    catalog.insertAdjacentHTML('afterend','<div id="work-empty" hidden><h3>没有匹配的项目</h3><p>可尝试“游戏”“服务”“视觉”或清空关键词。</p><button data-reset-search>查看全部作品</button></div>');
    let route='all';
    const explain={all:'10 个项目 · 产品、游戏、AI 工作流与数据体验。',product:'产品与服务 · 看用户任务、信息架构、触点与操作反馈。',game:'游戏交互 · 看场景、规则、输入和状态之间的连接。',ai:'AI 工作流 · 包含离线模型评测、AI 制作与朋辈 Agent 概念。各项目交付状态单独说明。',data:'数据体验 · 看信息编码、浏览节奏和视觉与数字的对应。'};
    function filter(){let n=0;const q=$('#work-query').value.toLowerCase().trim();$$('.portfolio-entry').forEach(e=>{const p=P.projects.find(p=>p.id===e.dataset.project),c=C[p.id];e.hidden=!(route==='all'||routes[route].includes(p.id))||!`${p.name}${p.cn}${p.summary}${p.tools.join(' ')}${c.tag}${c.lead}${c.action}`.toLowerCase().includes(q);if(!e.hidden)n++;});$('#work-empty').hidden=n>0;$('.route-description').textContent=q?`“${q}” · ${n} 个匹配项目`:explain[route];$('#filter-status').textContent=`显示 ${n} 个项目`;$$('[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.route===route)));}
    $$('[data-route]').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.route;filter();}));
    $$('[data-route-short]').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.routeShort;filter();}));
    $('#work-query').addEventListener('input',filter);$('#work-clear').addEventListener('click',()=>{$('#work-query').value='';filter();$('#work-query').focus();});
    $('[data-reset-search]').addEventListener('click',()=>{route='all';$('#work-query').value='';filter();});
  }
  const head=(title,task)=>`<div class="experience-heading"><div><p class="eyebrow">DESIGN IN ACTION / 交互体验</p><h2>${title}</h2></div><p>${task}</p></div>`;
  const bar=(name,status)=>`<div class="workbench-bar"><strong>${name}</strong><span>${status}</span></div>`;
  const foot=s=>`<p class="studio-boundary">${s}</p>`;
  const f={
    rallylens:()=>`${bar('RallyLens / Evidence workspace','原型界面 + 新增交互演示')}<div class="rally-workbench"><aside class="workspace-rail"><span>REVIEW<br>TOGETHER.</span>${buttons(['回放与事件','双方解释','计划协商'],'rally')}<p>记录来源、时间范围与未解决项。</p></aside><div class="rally-main"><div class="workspace-caption"><span data-rally-heading>回放与事件定位</span><span>G01_02 / Event 2</span></div><div data-rally-screen>${imageButton('rally-ui','原项目回放与事件界面')}</div><div class="rally-context"><span>方向 <b>P02 → P01</b></span><span>时间 <b>6.80 s</b></span><span>范围 <b>原项目示例事件</b></span></div><div data-plan-panel hidden><h3>双方保留独立的确认机会。</h3><p>讨论后的计划保持拟议状态；两人分别确认后才能成为双方确认。仍有分歧时可以留待继续讨论。</p><div class="confirmation-row"><label><input type="checkbox" data-confirm="a">伙伴 A 已确认</label><label><input type="checkbox" data-confirm="b">伙伴 B 已确认</label><button data-unresolved>保留未解决</button></div><output data-plan-state aria-live="polite">拟议 / 0 位确认</output></div></div><aside class="evidence-drawer"><span class="drawer-kicker">EVIDENCE / 来源</span><h3>把依据放在解释旁边。</h3><p data-rally-description>视频与人工事件提供时间和方向入口，用户可回查对应的练习片段。</p><label class="model-toggle"><input type="checkbox" data-model-toggle>展开模型候选</label><div data-model-drawer hidden><span>COMPUTED / 模型估计</span><dl><dt>Offer</dt><dd>3.39</dd><dt>Actual</dt><dd>3.95</dd></dl><p>目标有效性估计，模型尺度 0—100。两者分别描述供给与实际回应，不能据此推断公平或意图。</p></div><div class="evidence-legend"><span>○ 视频 / 事件</span><span>◇ 人的解释</span><span>△ 计算候选</span><span>? 未知保持可见</span></div></aside></div>${foot('界面图片与事件数值来自原项目；计划确认是本页交互重构示例，未写入研究记录。')}`,
    'privacy-city':()=>`${bar('Privacy City / Evaluation lab','5,000 合成样本 · 五模型比较')}<div class="evaluation-lab"><div class="evaluation-intro"><span class="huge-type">48<br><i>→</i> 1</span><div><span>48 → 64 → 32 → 1 / 5,249 PARAMETERS</span><h3>模型表现，需要从多个角度检查。</h3><p>训练／验证／测试分别为 3,500／750／750。选择指标查看同一轮五模型比较，完整结果始终可核对。</p></div></div>${buttons(['AUC / 排序','F1 / 分类','ECE / 校准','Brier / 概率误差'],'metric')}<div class="metric-reading"><h4 data-metric-title></h4><p data-metric-note></p></div><div data-metric-chart class="metric-chart"></div><div class="table-scroll"><table class="model-table"><caption>原实验五模型比较 · 5,000 合成样本 · 测试集 750</caption><thead><tr><th>模型</th><th>AUC ↑</th><th>F1 ↑</th><th>ECE ↓</th><th>Brier ↓</th></tr></thead><tbody>${modelRows.map(r=>`<tr><th>${r[0]}</th>${r.slice(1).map(n=>`<td>${n.toFixed(4)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>${foot('此表来自 5,000 样本离线实验，与报告中的 10,000 样本基线分别呈现。指标切换用于读图，不触发训练或收集访客的隐私行为。')}`,
    tennisatom:()=>`${bar('TennisAtom / Portrait director','观看动机 → 视觉表达')}<div class="portrait-director"><aside><span class="drawer-kicker">01 / 为什么观看</span><h3>一支属于<br>自己的影片。</h3>${buttons(['记录成长','感受动作','理解战术','表达情绪'],'motive')}<p data-motive-text></p></aside><div class="director-stage"><div class="director-live"><video id="director-video" src="media/tennis-1.mp4" poster="assets/tennis-real-1.webp" controls preload="metadata" playsinline aria-label="TennisAtom 既有真人成片"></video><span class="video-flag">EXISTING FILM / 真人成片</span></div><div class="film-switch" role="group" aria-label="选择真人成片">${[1,2,3,4,5].map((n,i)=>`<button data-studio-video="${i}" aria-pressed="${i===0}">${img('tennis-real-'+n,'真人成片 '+n)}<span>FILM / 0${n}</span></button>`).join('')}</div></div><aside class="director-material"><span class="drawer-kicker">02 / 视觉语法</span><div data-motive-art></div><h4 data-motive-title></h4><p>参与者的关键词、片段与节奏选择保留在制作流程里。</p></aside></div>${foot('动机选择说明原项目的设计映射；播放器展示五支既有成片，不在本页实时生成或改写视频。')}`,
    artemis:()=>`${bar('Artemis / Movement lab','依据原工程的移动检查规则')}<div class="game-lab"><div class="game-art">${img('artemis-world','原游戏世界观视觉')}<div class="game-art-title"><span>RETURN TO THE STARS</span><h3>一个指令，<br>先经过规则。</h3></div></div><div class="hex-controls"><div class="hex-board" role="group" aria-label="相邻六边形规则示例">${hexTiles.map((t,i)=>`<button class="hex-cell hex-${i}" data-studio-hex="${i}" aria-label="${t[0]}${t[1]}" style="--hex-x:${t[2]}%;--hex-y:${t[3]}%"><strong>${t[0]}</strong><span>${t[1]}</span></button>`).join('')}</div><div class="hex-legend"><span>◎ 当前格</span><span>× 不可行走</span><span>△ 高度差超限</span></div><div class="hex-inputs" role="group" aria-label="提交移动方向"><button data-studio-move="1">W ↑</button><button data-studio-move="4">A ←</button><button data-studio-move="3">S ↓</button><button data-studio-move="2">D →</button></div><div data-hex-result role="status"><span>WAITING / 等待输入</span><h4>选择一格，检查移动条件。</h4><p>示例的中心为当前格；目标格不实际移动，用于逐项检查规则。</p></div><button class="quiet-button" data-hex-reset>重置检查</button></div></div>${foot('格子为本次作品集的规则演示，不复原实机关卡。高度差 ≤ 1、IsWalkable 和边界检查依据当前脚本。下方展开实际状态机与构筑流程。')}`,
    bronze:()=>`${bar('天命：祀与戎 / 十集成片','原片、剧照与时间码')}<p>正在准备剧集浏览…</p>`,
    afterglow:()=>`${bar('AFTERGLOW / Encoding studio','手动设计演示 · 非站点实测')}<div class="encoding-studio"><div class="encoding-image">${img('afterglow-glyph','原项目最终视觉')}<div data-glyph-live class="glyph-live"></div><span>MANUAL ENCODING STUDY</span></div><div class="encoding-controls"><h3>调整信号，<br>读出对应变化。</h3>${[['人流','径向密度'],['噪声','振幅与变形'],['PM2.5','字号与外圈膨胀'],['风','倾斜与方向']].map((r,i)=>`<label>${r[0]}<output data-signal-out="${i}">50</output><input data-signal="${i}" aria-label="${r[0]}展示强度" type="range" min="0" max="100" value="50"><small>${r[1]} · 归一化展示强度 0—100</small></label>`).join('')}<button class="quiet-button" data-signal-reset>恢复中间状态</button></div></div>${foot('左侧是原项目视觉，右侧参数驱动新的编码示意。输入为手动归一化强度，没有物理单位，不代表实时环境观测。')}`,
    'growth-compass':()=>`${bar('Growth Compass / Service walkthrough','课程导航 · 作业支架 · 朋辈 Agent 概念')}<div class="service-workspace"><div class="service-nav"><span>LEARN<br>WITH A<br>DIRECTION.</span>${buttons(['选课前','学习中','朋辈问诊'],'service')}</div><div class="service-scene" data-service-scene></div><div class="service-logic"><span class="drawer-kicker">SERVICE BLUEPRINT</span><h3 data-service-title></h3><dl data-service-blueprint></dl><div class="agent-handoff"><span>朋辈导师 Agent / 原方案中的服务概念</span><label><input type="checkbox" data-peer-handoff>我需要进一步的人工问诊</label><output data-peer-status aria-live="polite">概念路径：作业画布 → 预审反馈 → 自主修改</output></div></div></div>${foot('依据服务体验设计源文件的 Growth Compass、模块化试听和互助式学习系统。故事板是设计情境；Agent 与课程内落地尚待试点。')}`,
    looplab:()=>`${bar('LoopLab / Material handoff','MVP 概念 · 本地交互演示')}<div class="material-workspace"><div class="material-visual">${img('loop-materials','原项目材料流转概念视觉')}<span>MATERIALS<br>IN CIRCULATION.</span></div><div class="material-transaction"><span class="drawer-kicker">01 / 查找与确认</span><h3>一次需求，<br>从规格开始。</h3><label>选择材料类别<select id="material-type"><option>板材 / 模型制作</option><option>纸材 / 印刷与装订</option><option>耗材 / 制作预约</option></select></label><dl><dt>需核对</dt><dd>尺寸、数量、状态与使用条件</dd><dt>服务方式</dt><dd>材料交换 / 团购 / 制作预约</dd><dt>履约触点</dt><dd>信息确认后安排线下交接</dd></dl><div class="handoff-steps"><span data-loop-step="0" class="current">选择</span><span data-loop-step="1">确认</span><span data-loop-step="2">取件准备</span></div><div data-material-result aria-live="polite"><h4>先选择需求类别。</h4><p>演示检查信息、预约与取件之间的衔接。</p></div><div class="transaction-actions"><button class="studio-primary" data-material-next>确认需求 →</button><button class="quiet-button" data-material-reset>重新开始</button></div></div></div>${foot('材料类别和交接状态用于说明服务流程，没有真实库存、订单或预约提交。原交付为竞品研究、MVP 范围与服务方案。')}`,
    baseball:()=>`${bar('Pitch / Impact / Interface atlas','原网站的三种阅读尺度')}<div class="atlas-workspace">${buttons(['人物入口','图表实验室','空间与数值'],'atlas')}<div data-atlas-screen>${imageButton('baseball-web-hero','原网站人物叙事首页')}</div><div class="atlas-copy"><h3 data-atlas-title>先认识球员，再进入表现。</h3><p data-atlas-text>大画面和人物章节建立叙事起点，图表在后续接续展开。</p></div></div>${foot('此处展示既有网站的真实截图。交互选择用于比较不同界面层级，不生成新比赛数据。')}`,
    garden:()=>`${bar('游园画境 / 网师园篇','团队游戏公开实机画面')}<div class="garden-source-viewer"><div data-garden-screen>${imageButton('garden-autumn','秋季探索 · 团队原游戏实机')}</div><div class="garden-viewer-caption">${buttons(['秋','冬','春','夏','绘梦奇扇','游览模式'],'garden')}<div data-garden-content aria-live="polite"><span>01 / AUTUMN</span><h3>从南宋秋景开始。</h3><p>与初任园主史正志相遇，探索任务与园景。</p></div></div></div><div class="garden-poem-demo"><span class="drawer-kicker">机制阅读 / 点击改字</span><div class="garden-poem-lines"><p><button data-garden-word="wind" aria-label="将雾来水面改为风来水面" aria-pressed="false">雾</button>来水面</p><p><button data-garden-word="moon" aria-label="将云到天心改为月到天心" aria-pressed="false">云</button>到天心</p></div><output data-garden-poem-result aria-live="polite">点击“雾”与“云”，查看公开介绍中的字义与园景对应。</output><button class="quiet-button" data-garden-poem-reset>还原诗句</button></div>${foot('画面来自团队公开介绍。切换与改字是本页的机制讲解演示，未运行原游戏；个人工作为 NPC、摄像机模块与小程序适配。')}`
  };
  const modelRows=[['NumPy MLP',.9857,.9613,.0337,.0392],['PyTorch MLP',.9853,.9739,.0249,.0341],['Random Forest',.9907,.9704,.0132,.0311],['Decision Tree',.9629,.9655,.0357,.0438],['Logistic Regression',.9723,.9059,.2507,.1152]];
  const hexTiles=[['◎','当前格',50,50],['W','可行走',50,20],['D','高度差 2',76,35],['S','不可行走',76,65],['A','可行走',24,35],['↙','可行走',24,65],['↘','地图边界',50,80]];
  function casePage(){
    const p=P.projects.find(p=>p.id===document.body.dataset.project);if(!p)return;
    const c=C[p.id];document.body.classList.add('studio-case');
    $('.case-hero').insertAdjacentHTML('afterend',`<section class="project-experience" id="experience" aria-labelledby="experience-title">${head(c.lead,c.action)}<div class="project-workbench">${f[p.id]()}</div></section>`);
    $('.experience-heading h2').id='experience-title';
    $('.case-toc').insertAdjacentHTML('afterbegin','<a class="experience-toc" href="#experience"><small>↗</small>TRY / 交互体验</a><a href="#design-decisions"><small>→</small>DESIGN / 设计决策</a>');
    $('.case-overview').insertAdjacentHTML('afterend',`<section class="design-decisions" id="design-decisions"><div class="decision-header"><p class="eyebrow">DESIGN DECISIONS / 从依据到界面</p><h2>设计选择，<br>都有对应的任务。</h2></div><div class="decision-list">${c.decisions.map((d,i)=>`<article><span>0${i+1}</span><div><h3>${d[0]}</h3><p>${d[1]}</p></div><small>${d[2]}</small></article>`).join('')}</div></section>`);
    if(c.assets.length){$('.case-result').insertAdjacentHTML('beforebegin',`<section class="asset-library" id="design-assets"><div class="asset-library-heading"><div><p class="eyebrow">DESIGN ASSETS / 既有项目物料</p><h2>把视觉成果展开看。</h2></div><div><button data-asset-direction="-1" aria-label="上一组项目物料">←</button><button data-asset-direction="1" aria-label="下一组项目物料">→</button></div></div><div class="asset-strip">${c.assets.map((a,i)=>`<figure>${imageButton(...a)}<figcaption><span>0${i+1}</span>${a[1]}</figcaption></figure>`).join('')}</div></section>`);$$('[data-asset-direction]').forEach(b=>b.addEventListener('click',()=>$('.asset-strip').scrollBy({left:+b.dataset.assetDirection*$('.asset-strip').clientWidth*.8,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'})));}
    const cover=$('.case-cover');if(c.cover)cover.innerHTML=img(c.cover,p.name+' 原项目成果','',true);
    $('.case-cover-caption').textContent=c.cover?'原项目视觉与界面素材':'场景探索与对话关系示意';
    bind(p.id);bindArt();
    const jump=document.createElement('a');jump.className='experience-jump';jump.href='#experience';jump.innerHTML='操作这个项目 <span>↓</span>';$('.case-meta').insertAdjacentElement('afterend',jump);
    const dock=document.createElement('nav');dock.className='case-section-dock';dock.setAttribute('aria-label','案例快速导航');dock.innerHTML=`<a href="index.html#work" aria-label="返回全部项目">←</a><a href="#experience">体验</a><a href="#design-decisions">设计</a><a href="#chapter-1">过程</a>${c.assets.length?'<a href="#design-assets">资产</a>':''}<a href="#project-results">交付</a>`;document.body.append(dock);
    const observed=$$('.project-experience,.design-decisions,.case-chapter,.asset-library,.case-result');
    const dockObserver=new IntersectionObserver(es=>{const visible=es.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);if(!visible.length)return;let hash=visible[0].target.id; if(hash.startsWith('chapter-'))hash='chapter-1';$$('a',dock).forEach(a=>{const current=a.hash==='#'+hash;a.classList.toggle('active',current);if(current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-5% 0px -60% 0px'});observed.forEach(s=>dockObserver.observe(s));
  }
  function bindArt(){document.addEventListener('click',e=>{const b=e.target.closest('[data-art]');if(!b)return;const d=$('#lightbox');$('img',d).src='assets/'+b.dataset.art+'.webp';$('img',d).alt=b.dataset.artCaption;$('p',d).textContent=b.dataset.artCaption;d.showModal();});}
  function bind(id){const r=$('.project-workbench');
    if(id==='rallylens'){
      const a=[['rally-ui','回放与事件定位','视频与人工事件提供时间和方向入口，用户可回查对应的练习片段。'],['rally-accounts','双方解释并列','原界面保留双方不同解释。各自陈述有自己的来源，意见无需被强行合并。'],['rally-timeline','从事件回到下一步计划','先检查时间范围和解释，再讨论下一次练习。计划可以保持未解决。']];
      $$('[data-studio-rally]',r).forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.studioRally;select(r,'rally',i);$('[data-rally-screen]',r).innerHTML=imageButton(a[i][0],a[i][1]);$('[data-rally-heading]',r).textContent=a[i][1];$('[data-rally-description]',r).textContent=a[i][2];$('[data-plan-panel]',r).hidden=i!==2;}));
      $('[data-model-toggle]',r).addEventListener('change',e=>$('[data-model-drawer]',r).hidden=!e.target.checked);
      $$('[data-confirm]',r).forEach(b=>b.addEventListener('change',()=>{const n=$$('[data-confirm]:checked',r).length;$('[data-plan-state]',r).textContent=n===2?'双方确认 / 示例计划':n===1?'讨论中 / 1 位确认':'拟议 / 0 位确认';}));
      $('[data-unresolved]',r).addEventListener('click',()=>{$$('[data-confirm]',r).forEach(b=>b.checked=false);$('[data-plan-state]',r).textContent='未解决 / 保留双方继续讨论的机会';});
    }
    if(id==='privacy-city'){
      const info=[['AUC · 在共同的 0—1 尺度上比较排序能力','越高越好。AUC 不需要先固定分类阈值；它不能说明输出概率是否可信。'],['F1 · 比较当前阈值下的分类表现','越高越好。F1 是 Precision 与 Recall 的调和平均，结果取决于分类阈值。'],['ECE · 比较分组概率与观察频率的差距','越低越好。分箱设置会影响 ECE，需要与分类、排序及其他校准指标一起读。'],['Brier · 比较概率预测的平方误差','越低越好。原项目二分类结果沿用共同设置，不能推断真实玩家场景中的泛化表现。']];
      function draw(i){$('[data-metric-title]',r).textContent=info[i][0];$('[data-metric-note]',r).textContent=info[i][1];$('[data-metric-chart]',r).innerHTML=`<div class="metric-axis"><span>0</span><span>0.5</span><span>1</span></div>${modelRows.map(m=>`<div class="metric-row"><span>${m[0]}</span><div class="metric-track"><i style="left:${m[i+1]*100}%"></i></div><b>${m[i+1].toFixed(4)}</b></div>`).join('')}`;$$('.model-table td',r).forEach((td,j)=>td.classList.toggle('metric-active',j%4===i));}
      $$('[data-studio-metric]',r).forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.studioMetric;select(r,'metric',i);draw(i);}));draw(0);
    }
    if(id==='tennisatom'){
      const a=[['tennis-real-5','记录时间与成长','以时间轴、片段档案和回看入口组织成长记录。'],['tennis-pose','感受动作与节奏','延伸轨迹、姿态结构与剪辑节奏突出身体动作。'],['tennis-trace','理解路径与战术','球场路径、分布和回放帮助检查具体运动信息。'],['tennis-impact','表达情绪与个人风格','参与者选择关键词、颜色和节奏；情绪含义由人表达。']];
      function motive(i){select(r,'motive',i);$('[data-motive-art]',r).innerHTML=imageButton(a[i][0],a[i][1]);$('[data-motive-title]',r).textContent=a[i][1];$('[data-motive-text]',r).textContent=a[i][2];}
      $$('[data-studio-motive]',r).forEach(b=>b.addEventListener('click',()=>motive(+b.dataset.studioMotive)));motive(0);
      $$('[data-studio-video]',r).forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.studioVideo;select(r,'video',i);const v=$('#director-video');v.pause();v.src=`media/tennis-${i+1}.mp4`;v.poster=`assets/tennis-real-${i+1}.webp`;v.load();}));
      $('#director-video').addEventListener('error',()=>$('.video-flag',r).textContent='视频暂不可播放 · 下方保留原项目成片与素材');
    }
    if(id==='artemis'){
      function check(i){const ok=[1,4,5].includes(i);$$('[data-studio-hex]',r).forEach(b=>{const selected=+b.dataset.studioHex===i;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});$('[data-hex-result]',r).innerHTML=`<span>${ok?'VALID / 目标通过':'REJECTED / 目标未提交'}</span><h4>${i===0?'当前格，无新路径':ok?'提交目标 → 起步 → 持续移动':i===2?'高度差 2，超过允许值 1':i===3?'IsWalkable 为 false':'目标超出地图边界'}</h4><p>${ok?'边界、可行走与高度条件满足。真实输入还需要满足冷却；到达最后目标后进入停步。':'此项检查失败，保持原目标；不会发起有效移动。'}</p>`;}
      const pad=$('.hex-controls',r);pad.tabIndex=0;pad.setAttribute('aria-label','移动规则演示，聚焦后可按 W A S D');pad.insertAdjacentHTML('afterbegin','<p class="hex-key-hint">点击格子或聚焦此区域后按 W A S D 检查规则。</p>');pad.addEventListener('keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey)return;const map={w:1,a:4,s:3,d:2};if(map[e.key.toLowerCase()]!==undefined){e.preventDefault();check(map[e.key.toLowerCase()]);}});
      $$('[data-studio-hex]',r).forEach(b=>b.addEventListener('click',()=>check(+b.dataset.studioHex)));$$('[data-studio-move]',r).forEach(b=>b.addEventListener('click',()=>check(+b.dataset.studioMove)));
      $('[data-hex-reset]',r).addEventListener('click',()=>{$$('[data-studio-hex]',r).forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});$('[data-hex-result]',r).innerHTML='<span>WAITING / 等待输入</span><h4>选择一格，检查移动条件。</h4><p>中心为当前格；规则示例不改变实机游戏。</p>';});
    }
    // The original-film browser for bronze is owned by bronze-film.js.
    if(id==='afterglow'){
      function draw(){
        const v=$$('[data-signal]',r).map(e=>+e.value);
        $$('[data-signal-out]',r).forEach((e,i)=>e.textContent=v[i]);
        const count=18+Math.round(v[0]*.7),amp=v[1]*.24;let paths='';
        for(let k=0;k<count;k++){
          const t=k/count*Math.PI*2,ri=65,ro=135+v[2]*.15+Math.sin(k*2.41)*amp;
          const x1=200+Math.cos(t)*ri,y1=200+Math.sin(t)*ri,x2=200+Math.cos(t+.16*v[3]/100)*ro,y2=200+Math.sin(t+.16*v[3]/100)*ro;
          paths+=`<path d="M${x1} ${y1}Q${200+Math.cos(t+.06)*(ri+ro)/2} ${200+Math.sin(t+.06)*(ri+ro)/2} ${x2} ${y2}"/>`;
        }
        $('[data-glyph-live]',r).innerHTML=`<svg viewBox="0 0 400 400" role="img" aria-label="手动强度生成的径向编码示意，非环境实测；PM2.5 改变字号与外圈，字重固定"><g fill="none" stroke="#e8e5d4" stroke-width="1.3">${paths}</g><circle cx="200" cy="200" r="48" stroke="#e1c234" fill="none"/><text x="200" y="205" text-anchor="middle" fill="#e8e5d4" font-family="Noto Sans SC" font-weight="500" font-size="${12+v[2]*.08}">余晖环</text></svg>`;
      }
      $$('[data-signal]',r).forEach(b=>b.addEventListener('input',draw));$('[data-signal-reset]',r).addEventListener('click',()=>{$$('[data-signal]',r).forEach(b=>b.value=50);draw();});draw();
    }
    if(id==='growth-compass'){
      const a=[['growth-tasting-original','课程预览先交代意义',[['学生行动','理解能力指向，体验模块后选择'],['前台触点','成长罗盘 / 模块化试听'],['后台工作','教师整理目标与案例；教务安排调整窗口']]],['growth-canvas-original','卡住时，先把问题说具体',[['学生行动','整理目标、证据、步骤与困难'],['前台触点','作业逻辑画布 / 正反案例'],['后台工作','教师维护案例；朋辈协助梳理方法']]],['growth-clinic-original','让预审反馈接到人的支持',[['学生行动','比较反馈，保留自主判断并寻求问诊'],['前台触点','朋辈导师 Agent 预审概念 / 人工问诊'],['后台工作','教师与朋辈整理规范；人工处理复杂情境']]]];
      function scene(i){select(r,'service',i);$('[data-service-scene]',r).innerHTML=imageButton(a[i][0],a[i][1]);$('[data-service-title]',r).textContent=a[i][1];$('[data-service-blueprint]',r).innerHTML=a[i][2].map(d=>`<dt>${d[0]}</dt><dd>${d[1]}</dd>`).join('');}
      $$('[data-studio-service]',r).forEach(b=>b.addEventListener('click',()=>scene(+b.dataset.studioService)));scene(0);$('[data-peer-handoff]',r).addEventListener('change',e=>$('[data-peer-status]',r).textContent=e.target.checked?'概念路径：整理问题 → 朋辈导师人工问诊 → 学生确认下一步':'概念路径：作业画布 → 预审反馈 → 自主修改');
    }
    if(id==='looplab'){
      let step=0;function update(){const type=$('#material-type',r).value;$$('[data-loop-step]',r).forEach((e,i)=>e.classList.toggle('current',i===step));$('[data-material-result]',r).innerHTML=`<h4>${['先选择需求类别。','需要进一步核对材料信息。','交接准备 / 概念状态'][step]}</h4><p>${[type+'：先确认尺寸、数量与使用条件。',type+'：确认规格和状态后再安排交接。','交接前核对材料、时间与责任。演示没有提交真实预约。'][step]}</p>`;$('[data-material-next]',r).disabled=step===2;$('[data-material-next]',r).textContent=['确认需求 →','安排交接 →','交接准备完成'][step];}
      $('[data-material-next]',r).addEventListener('click',()=>{step=Math.min(2,step+1);update();});$('[data-material-reset]',r).addEventListener('click',()=>{step=0;update();});$('#material-type',r).addEventListener('change',()=>{step=0;update();});update();
    }
    if(id==='baseball'){
      const a=[['baseball-web-hero','人物叙事入口','先认识球员，再进入表现。','大画面和人物章节建立叙事起点，图表在后续接续展开。'],['baseball-web-lab','图表实验室','多视角提供明确的探索入口。','图表分组保留任务与口径，帮助读者从概览选择问题。'],['baseball-web-detail','空间与指标细节','形状与数字一起解释一次表现。','位置分布承载空间信息，数值卡保留精确指标。']];
      $$('[data-studio-atlas]',r).forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.studioAtlas;select(r,'atlas',i);$('[data-atlas-screen]',r).innerHTML=imageButton(a[i][0],a[i][1]);$('[data-atlas-title]',r).textContent=a[i][2];$('[data-atlas-text]',r).textContent=a[i][3];}));
    }
    if(id==='garden'){
      const a=[['garden-autumn','AUTUMN','从南宋秋景开始。','与初任园主史正志相遇，探索任务与园景。'],['garden-winter','WINTER','冬季承接园林的低谷。','与史正志的儿子相遇，故事进入萧瑟的冬景。'],['garden-spring','SPRING','春景打开新的章节。','相同园林中的花木、任务与人物继续变化。'],['garden-summer','SUMMER','夏季接续园林复兴。','四季章节串联园景、历任园主与解谜任务。'],['garden-fan','DREAM-PAINTING FAN','诗句中的字，可以进入奇扇。','原实机展示提取与修改文字的界面；下方演示公开介绍中的两组改字关系。'],['garden-tour','TOUR MODE','照片与文字随游览展开。','自由漫步、切换四季，查看建筑与园林知识。']];
      $$('[data-studio-garden]',r).forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.studioGarden;select(r,'garden',i);$('[data-garden-screen]',r).innerHTML=imageButton(a[i][0],a[i][2]+'（团队原游戏画面）');$('[data-garden-content]',r).innerHTML=`<span>0${i+1} / ${a[i][1]}</span><h3>${a[i][2]}</h3><p>${a[i][3]}</p>`;}));
      const words=$$('[data-garden-word]',r);
      const poemResult=$('[data-garden-poem-result]',r);
      function explain(){const wind=words[0].getAttribute('aria-pressed')==='true',moon=words[1].getAttribute('aria-pressed')==='true';if(poemResult)poemResult.textContent=[wind?'风来水面：清风拂去池面浓雾。':'雾来水面：保留原来的雾景。',moon?'月到天心：明月出现，园主得以观月。':'云到天心：尚未唤出明月。'].join(' ');}
      words.forEach((b,i)=>b.addEventListener('click',()=>{const changed=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(changed));b.textContent=changed?['风','月'][i]:['雾','云'][i];b.setAttribute('aria-label',changed?['还原为雾来水面','还原为云到天心'][i]:['将雾来水面改为风来水面','将云到天心改为月到天心'][i]);explain();}));
      $('[data-garden-poem-reset]',r).addEventListener('click',()=>{words.forEach((b,i)=>{b.setAttribute('aria-pressed','false');b.textContent=['雾','云'][i];b.setAttribute('aria-label',['将雾来水面改为风来水面','将云到天心改为月到天心'][i]);});explain();});
    }
  }
  if($('#project-grid'))home();else casePage();
})();
